---
- hosts: otherservers
  become: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: remove apache
      apt: name=apache2 state=absent
    - name: install jdk
      apt: name=openjdk-8-jdk-headless state=present

- hosts: host2
  become: yes
  tasks:
    - name: Download the PostgreSQL 9.5.3 sources
      get_url: url=https://repo1.maven.org/maven2/postgresql/postgresql/9.1-901.jdbc4/postgresql-9.1-901.jdbc4.jar dest=./postgresql-9.1-901.jdbc4.jar mode=0755
#    - name: To connect to DB
#      shell: java -cp ./lib/postgresql-9.1-901.jdbc4.jar
#    - name: Ensure the PostgreSQL service is running
#      service: name=postgresql state=started enabled=yes

- hosts: host1
  become: yes
  tasks:
    - name: install tomcat8
      apt: name=tomcat8 state=present
    - name: install tomcat8admin
      apt: name=tomcat8-admin state=present
    - name: install git
      apt: name=git state=present 
    - name: install nodejs
      shell: apt-get install nodejs -y
    - name: install nodejs
      shell: apt-get install npm -y
    - name: create symbolic link
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link
    - name: clone repository
      git:
        repo: https://1191780@bitbucket.org/martalribeiro/devops_g2_maven.git
        dest: /home/vagrant/devops_g2_maven
    - name: change directory to project
      shell: cd devops_g2_maven/personalFinanceManagement
    - name: give permission to execute maven wrapper
      file:
        path: /home/vagrant/devops_g2_maven/personalFinanceManagement/mvnw
        owner: root
        group: root
        mode: "+rwx"
    - name: build jar
      shell: ./mvnw package -Dmaven.test.skip=true
    - name: give permission to execute jar file
      file:
        path: /home/vagrant/devops_g2_maven/personalFinanceManagement/target/devOpsProject-1.0-SNAPSHOT.jar
        owner: root
        group: root
        mode: "+rwx"
    - name: deploy the war file to tomcat8
      shell: cp target/devOpsProject-1.0-SNAPSHOT.jar /var/lib/tomcat8/webapps

