---
- hosts: otherservers
  become: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: remove apache
      apt: name=apache2 state=absent
    - name: install jdk
      apt: name=openjdk-8-jdk-headless state=present
- hosts: host1
  become: yes
  tasks:
    - name: install tomcat8
      apt: name=tomcat8 state=present
- hosts: host2
  become: yes
  tasks:
    - name: Download h2 database from maven.org
      get_url: url=https://repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar dest=./h2-1.4.200.jar mode=0755