@startuml
skinparam DefaultFontSize 20

participant ":RestClient"

participant ":SpringBoot"

participant "restcontroller:US005_1MemberAddCategoryToCategoryListControllerRest"

== Act ==
":RestClient" -> ":SpringBoot" :1:Post/Category \n ({ groupDescription :"SmithFamily",\n "personEmail:"ricky@gmail.com",\n"categoryDenomination:"shopping"})
activate ":SpringBoot" #FFBBBB

":SpringBoot"->"restcontroller:US005_1MemberAddCategoryToCategoryListControllerRest":1.1:create (groupDescription,personEmail,categoryDenomination) info:newcreateGroupCategoryInfoDTO
activate "restcontroller:US005_1MemberAddCategoryToCategoryListControllerRest" #FFBBBB

"restcontroller:US005_1MemberAddCategoryToCategoryListControllerRest"-> ":Assembler":1.2:createGroupCategoryInfoDTO(dto)
activate ":Assembler" #FFBBBB

":Assembler"->"service:US005_1MemberAddCategoryToCategoryListService":1.2.1categoryDTO=createGroupCategoryDTO
activate "service:US005_1MemberAddCategoryToCategoryListService" #FFBBBB
deactivate "service:US005_1MemberAddCategoryToCategoryListService" #FFBBBB

":Assembler"->"service:US005_1MemberAddCategoryToCategoryListService":1.2.1.2:categoryDTOresult=addCategoryDTOgroup(categoryDTO)
activate "service:US005_1MemberAddCategoryToCategoryListService" #FFBBBB
deactivate "service:US005_1MemberAddCategoryToCategoryListService" #FFBBBB

"restcontroller:US005_1MemberAddCategoryToCategoryListControllerRest"--> ":SpringBoot":1.3:ResponseEntity<CategoryDTO>
activate ":SpringBoot" #FFBBBB

":SpringBoot"-->":RestClient":1.4:result, HttpStatus.CREATED

deactivate "service:US005_1MemberAddCategoryToCategoryListService"
deactivate "restcontroller:US005_1MemberAddCategoryToCategoryListControllerRest"

@enduml