@startuml
skinparam DefaultFontSize 20


== Act ==
autonumber
[-> "service:\nUS005_1AdminAddCategoryToCategoryService" : createGroupCategory\n(createGroupCategoryDTO)
activate "service:\nUS005_1AdminAddCategoryToCategoryService" #FFBBBB
autonumber 1.1
"service:\nUS005_1AdminAddCategoryToCategoryService" -> "createGroupCategoryDTO: \nCreateGroupCategoryDTO" : personEmail = getPersonEmail()
activate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB
deactivate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB

"service:\nUS005_1AdminAddCategoryToCategoryService" -> "createGroupCategoryDTO: \nCreateGroupCategoryDTO" : groupDescription = getGroupDescription())
activate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB
deactivate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB

"service:\nUS005_1AdminAddCategoryToCategoryService" -> "createGroupCategoryDTO: \nCreateGroupCategoryDTO" : categoryDenomination = getAccountDenomination()
activate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB
deactivate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB


"service:US005_1AdminAddCategoryToCategoryService"->"groupRep:GroupRepository":group = findGroupByDescription\n(groupDescription)
activate "groupRep:GroupRepository" #FFBBBB
deactivate "groupRep:GroupRepository"

"service:US005_1AdminAddCategoryToCategoryService"->"personRep:PersonRepository": person = findPersonByEmail(personEmail)
activate "personRep:PersonRepository" #FFBBBB
deactivate "personRep:PersonRepository"

"service:US005_1AdminAddCategoryToCategoryService"->"person:Person": personID = getID()
activate "person:Person" #FFBBBB
deactivate "person:Person"

"service:US005_1AdminAddCategoryToCategoryService"->"group:Group": validateAdmin = isGroupAdmin(personID)
activate "group:Group" #FFBBBB
deactivate "group:Group"

"service:US005_1AdminAddCategoryToCategoryService"->"group:Group": groupID = getID()
activate "group:Group" #FFBBBB
deactivate "group:Group"

"service:US005_1AdminAddCategoryToCategoryService"->"categoryRep:CategoryRepository":isCategoryCreated = createCategory(categoryDenomination, groupID)
activate "categoryRep:CategoryRepository" #FFBBBB

create "category:Category"
"categoryRep:CategoryRepository"->"category:Category":new Category\n(categoryDenomination, groupID)
"categoryRep:CategoryRepository"->"categoryRep:CategoryRepository": add(category)

deactivate "categoryRep:CategoryRepository"
deactivate "service:US005_1AdminAddCategoryToCategoryService"


@enduml