@startuml

skinparam DefaultFontSize 20

title US003 Sequence Diagram - Happy Case

participant "HTTP Client :Test"
participant "mvcResult :MvcResult"
participant "response :MockHttpServletResponse"
participant ":SpringBoot"
participant "restController:US003AddMemberToGroupControllerRest"
participant "service:US003AddMemberToGroupService"
participant ":GroupDTOAssembler"
participant "personRep:PersonRepository"
participant "groupsRep:GroupsRepository"
participant "group:Group"





== Act ==

autonumber
"HTTP Client :Test" -> ":SpringBoot": POST = /addMemberToGroup ,\n  body {personEmail, groupDescription}
activate "HTTP Client :Test" #FFBBBB

autonumber 1.1

activate ":SpringBoot" #FFBBBB

":SpringBoot" -> ":SpringBoot" : deserialize (body {personEmail, groupDescription})
activate ":SpringBoot" #FFBBBB

autonumber 1.1.1
create "addMemberInfoDTO: AddMemberInfoDTO"
":SpringBoot" --> "addMemberInfoDTO: AddMemberInfoDTO" : create (personEmail, groupDescription)
deactivate ":SpringBoot"

autonumber 1.2
":SpringBoot" -> "restController:US003AddMemberToGroupControllerRest" : addMember (addMemberInfoDTO)

autonumber 1.2.1
activate "restController:US003AddMemberToGroupControllerRest" #FFBBBB
"restController:US003AddMemberToGroupControllerRest" -> ":GroupDTOAssembler": addMemberDTO = transformIntoAddMemberDTO(addMemberInfoDTO)

autonumber 1.2.1.1

activate ":GroupDTOAssembler" #FFBBBB

":GroupDTOAssembler" -> "addMemberInfoDTO: AddMemberInfoDTO": personEmail = getPersonEmail()

activate "addMemberInfoDTO: AddMemberInfoDTO" #FFBBBB
deactivate "addMemberInfoDTO: AddMemberInfoDTO" #FFBBBB

":GroupDTOAssembler" -> "addMemberInfoDTO: AddMemberInfoDTO": groupDescription = getGroupDescription()
activate "addMemberInfoDTO: AddMemberInfoDTO" #FFBBBB
deactivate "addMemberInfoDTO: AddMemberInfoDTO" #FFBBBB

create "addMemberDTO:AddMemberDTO"
":GroupDTOAssembler" -> "addMemberDTO:AddMemberDTO": addMemberDTO = new AddMemberDTO(personEmail,groupDescription)
deactivate ":GroupDTOAssembler"

autonumber 1.2.2
"restController:US003AddMemberToGroupControllerRest" -> "service:US003AddMemberToGroupService" : addedMemberDTO = createGroup(addMemberDTO)


autonumber 1.2.2.1
activate "service:US003AddMemberToGroupService" #FFBBBB
"service:US003AddMemberToGroupService" -> "addMemberDTO:AddMemberDTO" : personEmail = getPersonEmail()
activate "addMemberDTO:AddMemberDTO" #FFBBBB
deactivate "addMemberDTO:AddMemberDTO"

"service:US003AddMemberToGroupService" -> "personRep:PersonRepository" : person = findPersonByEmail (personEmail)
activate "personRep:PersonRepository" #FFBBBB
deactivate "personRep:PersonRepository"

"service:US003AddMemberToGroupService" -> "addMemberDTO:AddMemberDTO" : groupDescription = getGroupDescription()
activate "addMemberDTO:AddMemberDTO" #FFBBBB
deactivate "addMemberDTO:AddMemberDTO"

"service:US003AddMemberToGroupService" -> "groupsRep:GroupsRepository" : group = findGroupByDescription(groupDescription)
activate "groupsRep:GroupsRepository" #FFBBBB

autonumber 1.2.2.4.1

"groupsRep:GroupsRepository" -> "group:Group" : boolean wasMemberAdded = add(person)
activate "group:Group" #FFBBBB
deactivate "groupsRep:GroupsRepository" #FFBBBB
deactivate "group:Group" #FFBBBB

autonumber 1.2.2.5
"service:US003AddMemberToGroupService" -> ":GroupDTOAssembler" : addedMemberDTO = addMemberDTO (groupID)
activate ":GroupDTOAssembler" #FFBBBB

autonumber 1.2.2.5.1
create "addedMemberDTO:AddedMemberDTO"
":GroupDTOAssembler" -> "addedMemberDTO:AddedMemberDTO" : new AddedMemberDTO(wasMemberAdded, person, group)

deactivate ":GroupDTOAssembler"
deactivate "service:US003AddMemberToGroupService"

autonumber 1.3
return responseEntity (addedMemberDTO, HttpStatus.CREATED)

deactivate "restController:US003AddMemberToGroupControllerRest"

"HTTP Client :Test" <-- ":SpringBoot" : mvcResultJson
deactivate ":SpringBoot"

autonumber 2
|||
"HTTP Client :Test" -> "HTTP Client :Test" : deserialize (mvcResultJson)
activate "HTTP Client :Test" #FFBBBB

autonumber 2.1
"HTTP Client :Test" --> "mvcResult :MvcResult" : mvcResult = new MvcResult (mvcResultJson)
deactivate "HTTP Client :Test"

|||

autonumber 3
"HTTP Client :Test" -> "mvcResult :MvcResult" : response = getResponse()

autonumber 3.1

activate "mvcResult :MvcResult" #FFBBBB
"mvcResult :MvcResult" -> "response :MockHttpServletResponse" : response = new MockHttpServletResponse()
deactivate "mvcResult :MvcResult"

autonumber 4
"HTTP Client :Test" -> "response :MockHttpServletResponse" : status = getStatus()
activate "response :MockHttpServletResponse" #FFBBBB
"HTTP Client :Test" -> "response :MockHttpServletResponse" : result = getContentAsString()
deactivate "response :MockHttpServletResponse" #FFBBBB
== Assert ==

"HTTP Client :Test" -> "HTTP Client :Test" : assertEquals(201, status)
"HTTP Client :Test" -> "HTTP Client :Test" : assertEquals(expectedResult, result)
deactivate "HTTP Client :Test"

@enduml

