@startuml
skinparam DefaultFontSize 20

participant "test:RestClient"

participant ":SpringBoot"

== Act ==
":RestClient" -> ":SpringBoot" :1:Post/addCategoryToGroup \n ({ groupDescription :"SmithFamily",\n "personEmail:"ricky@gmail.com",\n"categoryDenomination:"shopping"})
activate ":SpringBoot" #FFBBBB

create "info:GroupCategoryInfoDTO"
":SpringBoot"->"info:GroupCategoryInfoDTO":1.1:create (groupDescription,\n personEmail,categoryDenomination)
activate "restController:US005_1AdminAddsCategoryControllerRest" #FFBBBB

create "restController:US005_1AdminAddsCategoryControllerRest"
":SpringBoot"-> "restController:US005_1AdminAddsCategoryControllerRest":1.2: addCategoryToGroup(info)



"restController:US005_1AdminAddsCategoryControllerRest"-> ":CategoryDTOAssembler":1.2.1:createGroupCategoryDTO =\n transformToCreateGroupCategoryDTO(info)
activate ":CategoryDTOAssembler" #FFBBBB

create "categoryDTO:CategoryDTO"
":CategoryDTOAssembler"-->"categoryDTO:CategoryDTO":1.2.2:categoryDTO=\n createGroupCategoryDTO(createGroupCategoryDTO)
deactivate ":CategoryDTOAssembler"

"restController:US005_1AdminAddsCategoryControllerRest"->"service:US005_1AdminAddsCategoryToGroupService":1.2.3:categoryDTOresult=\naddCategoryDTOgroup(categoryDTO)
activate "service:US005_1AdminAddsCategoryToGroupService" #FFBBBB
deactivate "service:US005_1AdminAddsCategoryToGroupService" #FFBBBB

ref over "service:US005_1AdminAddsCategoryToGroupService": init

"restController:US005_1AdminAddsCategoryControllerRest"--> ":SpringBoot":1.3:responseEntity=responseEntity<>(CategoryDTO,HttpStatus.CREATED)
":SpringBoot"-->"test:RestClient":1.3.1:mvcResult

"test:RestClient" -> ":SpringBoot": 1.3.2:response = mvcResult.getResponse()

"test:RestClient"-> ":SpringBoot":1.3.3: status = response.getStatus()

"test:RestClient" -> ":SpringBoot":1.3.4: result = response.getContentAsString()

== Assert ==

"test:RestClient" -> "test:RestClient" : assertEquals(201, status)
"test:RestClient" -> "test:RestClient" : assertEquals(expectedResult, result)
deactivate "service:US005_1AdminAddsCategoryToGroupService"
deactivate "restController:US005_1AdminAddsCategoryControllerRest"

@enduml