@startuml
skinparam DefaultFontSize 20
title US005.1 Sequence Diagram - Happy Case

participant "HTTP Client :Test"
participant "mvcResult :MvcResult"
participant "response :MockHttpServletResponse"
participant ":SpringBoot"

== Act ==
autonumber
"HTTP Client :Test" -> ":SpringBoot" :1:Post/addCategoryToGroup \n ({ groupDescription :"SmithFamily",\n "personEmail:"ricky@gmail.com",\n"categoryDenomination:"shopping"})
activate ":SpringBoot" #FFBBBB

autonumber 1.1
create "info:GroupCategoryInfoDTO"
":SpringBoot"->"info:GroupCategoryInfoDTO":create (groupDescription,\n personEmail,categoryDenomination)
activate "restController:US005_1AdminAddsCategoryControllerRest" #FFBBBB


create "restController:US005_1AdminAddsCategoryControllerRest"
":SpringBoot"-> "restController:US005_1AdminAddsCategoryControllerRest": addCategoryToGroup(info)



"restController:US005_1AdminAddsCategoryControllerRest"-> ":CategoryDTOAssembler":createGroupCategoryDTO =\n transformToCreateGroupCategoryDTO(info)
activate ":CategoryDTOAssembler" #FFBBBB

create "createGroupCategoryDTO:CreateGroupCategoryDTO"
":CategoryDTOAssembler"-->"createGroupCategoryDTO:CreateGroupCategoryDTO":new CreateGroupCategoryDTO\n(info.getGroupDescription(),\ninfo.getPersonEmail(),\n info.getCategoryDenomination())
deactivate ":CategoryDTOAssembler"

"restController:US005_1AdminAddsCategoryControllerRest"->"service:US005_1AdminAddsCategoryToGroupService":categoryDTOresult=\naddCategoryDTOgroup(createGroupCategoryDTO)
activate "service:US005_1AdminAddsCategoryToGroupService" #FFBBBB
deactivate "service:US005_1AdminAddsCategoryToGroupService" #FFBBBB

ref over "service:US005_1AdminAddsCategoryToGroupService": init

"restController:US005_1AdminAddsCategoryControllerRest"--> ":SpringBoot":responseEntity=responseEntity<>(CategoryDTO,HttpStatus.CREATED)
deactivate "restController:US005_1AdminAddsCategoryControllerRest"

"HTTP Client :Test" <-- ":SpringBoot" : mvcResultJson
deactivate ":SpringBoot"

autonumber 2
|||
"HTTP Client :Test" -> "HTTP Client :Test" : deserialize (mvcResultJson)
activate "HTTP Client :Test"

autonumber 2.1
"HTTP Client :Test" --> "mvcResult :MvcResult" : mvcResult = new MvcResult (mvcResultJson)
deactivate "HTTP Client :Test"

|||

autonumber 3
"HTTP Client :Test" -> "mvcResult :MvcResult" : response = getResponse()

autonumber 3.1

activate "mvcResult :MvcResult" #FFBBBB
"mvcResult :MvcResult" -> "response :MockHttpServletResponse" : response = new MockHttpServletResponse()
deactivate "mvcResult :MvcResult"

autonumber 4
"HTTP Client :Test" -> "response :MockHttpServletResponse" : status = getStatus()
activate "response :MockHttpServletResponse" #FFBBBB
"HTTP Client :Test" -> "response :MockHttpServletResponse" : result = getContentAsString()
deactivate "response :MockHttpServletResponse" #FFBBBB



== Assert ==

"HTTP Client :Test" -> "HTTP Client :Test" : assertEquals(201, status)
"HTTP Client :Test" -> "HTTP Client :Test" : assertEquals(expectedResult, result)

deactivate ":SpringBoot"
deactivate "service:US005_1AdminAddsCategoryToGroupService"
deactivate "restController:US005_1AdminAddsCategoryControllerRest"

@enduml