@startuml

skinparam DefaultFontSize 20

title US003 Sequence Diagram - Happy Case

participant "HTTP Client (Test)"
participant "resultAction:ResultAction"
participant "inputDTO:\naddMemberInfoDTO"
participant "postRequest:\nRequestBuilder"
participant "mvcResult :MvcResult"
participant "mvc:MockMvc"
participant "restController:US003AddMemberToGroupControllerRest"
participant "service:US003AddMemberToGroupService"
participant ":GroupDTOAssembler"
participant "personRep:PersonRepository"
participant "groupsRep:GroupsRepository"
participant "group:Group"



create "inputDTO:\naddMemberInfoDTO"
activate "HTTP Client (Test)" #FFBBBB
"HTTP Client (Test)" -> "inputDTO:\naddMemberInfoDTO": inputDTO = new AddMemberInfoDTO\n(personEmail, groupDescription);
"HTTP Client (Test)" -> "HTTP Client (Test)": inputJson = mapToJson(inputDTO)

== Act ==

create "postRequest:\nRequestBuilder"
"HTTP Client (Test)" -> "postRequest:\nRequestBuilder" : postRequest = POST=/addMember {inputJson}

create "mvc:MockMvc"
"HTTP Client (Test)" -> "mvc:MockMvc" : perform(postRequest)
activate "mvc:MockMvc"  #FFBBBB

autonumber 4.1
"mvc:MockMvc" -> "mvc:MockMvc" :  deserialize inputJson

create "infoDTO:CreatePersonAccountInfoDTO"
"mvc:MockMvc"->"infoDTO:CreatePersonAccountInfoDTO": create

create "restController:US003AddMemberToGroupControllerRest"
"mvc:MockMvc"-> "restController:US003AddMemberToGroupControllerRest" : addMember (addMemberInfoDTO)

autonumber 1.2.1
activate "restController:US003AddMemberToGroupControllerRest" #FFBBBB
"restController:US003AddMemberToGroupControllerRest" -> ":GroupDTOAssembler": addMemberDTO = transformIntoAddMemberDTO(addMemberInfoDTO)

autonumber 1.2.1.1

activate ":GroupDTOAssembler" #FFBBBB

":GroupDTOAssembler" -> "addMemberInfoDTO: AddMemberInfoDTO": personEmail = getPersonEmail()

activate "addMemberInfoDTO: AddMemberInfoDTO" #FFBBBB
deactivate "addMemberInfoDTO: AddMemberInfoDTO" #FFBBBB

":GroupDTOAssembler" -> "addMemberInfoDTO: AddMemberInfoDTO": groupDescription = getGroupDescription()
activate "addMemberInfoDTO: AddMemberInfoDTO" #FFBBBB
deactivate "addMemberInfoDTO: AddMemberInfoDTO" #FFBBBB

create "addMemberDTO:AddMemberDTO"
":GroupDTOAssembler" -> "addMemberDTO:AddMemberDTO": addMemberDTO = new AddMemberDTO(personEmail,groupDescription)
deactivate ":GroupDTOAssembler"

autonumber 1.2.2
"restController:US003AddMemberToGroupControllerRest" -> "service:US003AddMemberToGroupService" : addedMemberDTO = createGroup(addMemberDTO)


autonumber 1.2.2.1
activate "service:US003AddMemberToGroupService" #FFBBBB
"service:US003AddMemberToGroupService" -> "addMemberDTO:AddMemberDTO" : personEmail = getPersonEmail()
activate "addMemberDTO:AddMemberDTO" #FFBBBB
deactivate "addMemberDTO:AddMemberDTO"

"service:US003AddMemberToGroupService" -> "personRep:PersonRepository" : person = findPersonByEmail (personEmail)
activate "personRep:PersonRepository" #FFBBBB
deactivate "personRep:PersonRepository"

"service:US003AddMemberToGroupService" -> "addMemberDTO:AddMemberDTO" : groupDescription = getGroupDescription()
activate "addMemberDTO:AddMemberDTO" #FFBBBB
deactivate "addMemberDTO:AddMemberDTO"

"service:US003AddMemberToGroupService" -> "groupsRep:GroupsRepository" : group = findGroupByDescription(groupDescription)
activate "groupsRep:GroupsRepository" #FFBBBB

autonumber 1.2.2.4.1

"groupsRep:GroupsRepository" -> "group:Group" : boolean wasMemberAdded = add(person)
activate "group:Group" #FFBBBB
deactivate "groupsRep:GroupsRepository" #FFBBBB
deactivate "group:Group" #FFBBBB

autonumber 1.2.2.5
"service:US003AddMemberToGroupService" -> ":GroupDTOAssembler" : addedMemberDTO = addMemberDTO (groupID)
activate ":GroupDTOAssembler" #FFBBBB

autonumber 1.2.2.5.1
create "addedMemberDTO:AddedMemberDTO"
":GroupDTOAssembler" -> "addedMemberDTO:AddedMemberDTO" : new AddedMemberDTO(wasMemberAdded, person, group)

deactivate ":GroupDTOAssembler"
deactivate "service:US003AddMemberToGroupService"

autonumber 1.3
return responseEntity = responseEntity<> (addedMemberDTO, HttpStatus.CREATED)

deactivate "restController:US003AddMemberToGroupControllerRest"

autonumber 4.4
"mvc:MockMvc" -> "mvc:MockMvc" : serialize responseEntity
create "resultAction:ResultAction"
"resultAction:ResultAction" <-- "mvc:MockMvc" : create
activate "resultAction:ResultAction" #FFBBBB
deactivate "mvc:MockMvc"

autonumber 5
"HTTP Client (Test)" -> "resultAction:ResultAction" : mvcResult = andReturn()

create "mvcResult :MvcResult"
autonumber 5.1
"resultAction:ResultAction" -> "mvcResult :MvcResult" : create
deactivate "resultAction:ResultAction"

autonumber 6
"HTTP Client (Test)" -> "mvcResult :MvcResult" : response = getResponse
activate "mvcResult :MvcResult" #FFBBBB
deactivate "mvcResult :MvcResult"

"HTTP Client (Test)" -> "mvcResult :MvcResult" : status = getStatus()
activate "mvcResult :MvcResult" #FFBBBB
deactivate "mvcResult :MvcResult"

"HTTP Client (Test)" -> "mvcResult :MvcResult" : result = getContentAsString()
activate "mvcResult :MvcResult" #FFBBBB
deactivate "mvcResult :MvcResult"

== Assert ==

"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(201, status)
"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(expectedResult, result)

@enduml