@startuml
skinparam DefaultFontSize 20

== Act ==

"service:US005.1MemberAddCategoryToCategoryListService"->"groupRep:GroupRepository":group = findGroupByDescription\n(groupDescription)
activate "groupRep:GroupRepository" #FFBBBB
deactivate "groupRep:GroupRepository"

"service:US005.1MemberAddCategoryToCategoryListService"->"personRep:PersonRepository": person = findPersonByEmail(personEmail)
activate "personRep:PersonRepository" #FFBBBB
deactivate "personRep:PersonRepository"

"service:US005.1MemberAddCategoryToCategoryListService"->"person:Person": personID = getID()
activate "person:Person" #FFBBBB
deactivate "person:Person"

"service:US005.1MemberAddCategoryToCategoryListService"->"group:Group": validateAdmin = isGroupAdmin(personID)
activate "group:Group" #FFBBBB
deactivate "group:Group"

"service:US005.1MemberAddCategoryToCategoryListService"->"group:Group": groupID = getID()
activate "group:Group" #FFBBBB
deactivate "group:Group"

"service:US005.1MemberAddCategoryToCategoryListService"->"categoryRep:CategoryRepository":isCategoryCreated = createCategory(categoryDenomination, groupID)
activate "categoryRep:CategoryRepository" #FFBBBB

create "category:Category"
"categoryRep:CategoryRepository"->"category:Category":new Category\n(categoryDenomination, groupID)
"categoryRep:CategoryRepository"->"categoryRep:CategoryRepository": add(category)

deactivate "categoryRep:CategoryRepository"
deactivate "service:US005.1MemberAddCategoryToCategoryListService"


@enduml