@startuml
skinparam DefaultFontSize 20
title US007 Sequence Diagram - Happy Case

participant "HTTP Client :Test"
participant "mvcResult :MvcResult"

participant "mvc: MockMvc"

== Act ==


autonumber
"HTTP Client :Test" -> "mvc: MockMvc" :Post /addGroupAccount \n ({ groupDescription :"SmithFamily",\n "personEmail:"ricky@gmail.com",\n"accountDenomination:"shopping", \n accountDescription:"shopping expenses"})
activate "mvc: MockMvc" #FFBBBB

activate "HTTP Client :Test" #FFBBBB

autonumber 1.1
create "info:createGroupAccountInfoDTO"

"mvc: MockMvc"-->"info:createGroupAccountInfoDTO" : create

create "restController:US007CreateGroupAccountControllerRest"
"mvc: MockMvc"-> "restController:US007CreateGroupAccountControllerRest": createGroupAccountDTO (info)
activate "restController:US007CreateGroupAccountControllerRest" #FFBBBB

"restController:US007CreateGroupAccountControllerRest"-> ":AccountDTOAssembler":createGroupAccountDTO =\n transformToCreateGroupAccountDTO(info)
activate ":AccountDTOAssembler" #FFBBBB

create "createGroupAccountDTO:CreateGroupAccountDTO"
":AccountDTOAssembler"-->"createGroupAccountDTO:CreateGroupAccountDTO":new CreateGroupAccountDTO\n(info.getGroupDescription(),\n info.getPersonEmail(),\n info.getAccountDenomination(), \n info.getAccountDescription())
deactivate ":AccountDTOAssembler"

"restController:US007CreateGroupAccountControllerRest"->"service:US007CreateGroupAccountService":accountDTO result= \n addAccountDTOGroup(createGroupCategoryDTO)
activate "service:US007CreateGroupAccountService" #FFBBBB
deactivate "service:US007CreateGroupAccountService" #FFBBBB

ref over "service:US007CreateGroupAccountService": US007CreateGroupAccountControllerRest_Part2

"restController:US007CreateGroupAccountControllerRest"--> "mvc: MockMvc":responseEntity=responseEntity<>(AccountDTO,HttpStatus.CREATED)
deactivate "restController:US007CreateGroupAccountControllerRest"

"HTTP Client :Test" <-- "mvc: MockMvc" : jsonResponse
deactivate "mvc: MockMvc"

autonumber 2
|||
"HTTP Client :Test" -> "HTTP Client :Test" : mvcResult = andReturn()

create "mvcResult :MvcResult"

"HTTP Client :Test" --> "mvcResult :MvcResult": create
activate "mvcResult :MvcResult" #FFBBBB
autonumber 3
"HTTP Client :Test" -> "mvcResult :MvcResult" : response = getResponse()


autonumber 4
"HTTP Client :Test" -> "mvcResult :MvcResult" : status = getStatus()



"HTTP Client :Test" -> "mvcResult :MvcResult" : result = getContentAsString()

deactivate "mvcResult :MvcResult" #FFBBBB

== Assert ==

"HTTP Client :Test" -> "HTTP Client :Test" : assertEquals(201, status)
"HTTP Client :Test" -> "HTTP Client :Test" : assertEquals(expectedResult, result)

deactivate "mvc: MockMvc"
deactivate "service:US007CreateGroupAccountService"
deactivate "restController:US007CreateGroupAccountControllerRest"

@enduml