@startuml
skinparam DefaultFontSize 25

autonumber 1
"service:US008CreateTransactionService" -> "ledger:Ledger" : ledger = getByID(personID)
activate "ledger:Ledger" #FFBBBB
deactivate "ledger:Ledger"

"service:US008CreateTransactionService" -> "categoryRepo:CategoryRepository" : categoryID = getByID(categoryID)
activate "categoryRepo:CategoryRepository" #FFBBBB
deactivate "categoryRepo:CategoryRepository"

"service:US008CreateTransactionService" -> "accountRepo:AccountRepository" : accountFrom = getByID(accountFromID)
activate "accountRepo:AccountRepository" #FFBBBB
deactivate "accountRepo:AccountRepository"

"service:US008CreateTransactionService" -> "accountRepo:AccountRepository" : accountTo = getByID(accountToID)
activate "accountRepo:AccountRepository" #FFBBBB
deactivate "accountRepo:AccountRepository"
deactivate "service:US008CreateTransactionService" #FFBBBB

@enduml
