@startuml
skinparam DefaultFontSize 20
participant ":Test"
participant "controller:US004GetFamilyGroupsController"

==Act==
":Test" -> "controller:US004GetFamilyGroupsController" : families = getFamilyGroups()
activate "controller:US004GetFamilyGroupsController" #FFBBBB

participant "service:US004GetFamilyGroupsService"
"controller:US004GetFamilyGroupsController" -> "service:US004GetFamilyGroupsService" : families = getFamilyGroups()
activate "service:US004GetFamilyGroupsService" #FFBBBB

participant "groupsRepository:GroupsRepository"
"service:US004GetFamilyGroupsService" -> "groupsRepository:GroupsRepository" : families = returnOnlyFamilies()
activate "groupsRepository:GroupsRepository" #FFBBBB

participant "group:Group"

"groupsRepository:GroupsRepository" -> "group:Group" : family = isFamily()
activate "group:Group" #FFBBBB
deactivate "group:Group"
deactivate "controller:US004GetFamilyGroupsController"
deactivate "service:US004GetFamilyGroupsService"
deactivate "groupsRepository:GroupsRepository"
==Assert==

":Test" -> ":Test" : assertEquals(expected, families)


@enduml
