@startuml

skinparam DefaultFontSize 20

create ":Test"

== Arrange ==
create "controller:AdminCreatesCategoryController"
":Test" -> "controller:AdminCreatesCategoryController" : new AdminCreatesCategoryController()
participant "group1:Group"

== Act ==
":Test" -> "controller:AdminCreatesCategoryController" : createCategory\n(nameOfCategory, oneGroup, categoryCreator)
activate "controller:AdminCreatesCategoryController" #FFBBBB
"controller:AdminCreatesCategoryController" -> "group1:Group" : createAndAddCategoryToCategoryList\n(nameOfCategory, categoryCreator)
activate "group1:Group" #FFBBBB
"group1:Group" -> "categoriesList :CategoryList" : addCategoryToCategoryList(nameOfCategory)
activate "categoriesList :CategoryList" #FFBBBB
create "category1:Category"
"categoriesList :CategoryList" -> "category1:Category" : new Category(nameOfCategory)
"categoriesList :CategoryList"-> "categoriesList :CategoryList" : add(category1)
"categoriesList :CategoryList" --> "group1:Group" : categoryCreated
deactivate "categoriesList :CategoryList" #FFBBBB
"group1:Group" --> "controller:AdminCreatesCategoryController" : categoryCreated
deactivate "group1:Group" #FFBBBB
"controller:AdminCreatesCategoryController" --> ":Test" : categoryCreated
deactivate "controller:AdminCreatesCategoryController" #FFBBBB

== Assert ==
":Test" -> ":Test" : assertTrue(categoryCreated)

@enduml