 @startuml
skinparam DefaultFontSize 20
participant ":Test"

== Arrange ==

create "controller:GetPersonalAndGroupTransactionsInDateRangeController"
":Test" -> "controller:GetPersonalAndGroupTransactionsInDateRangeController" : new GetPersonalAndGroup\nTransactionsInDateRangeController

participant "person:Person"
participant "personalLedger:Ledger"
participant "groupsList:GroupsList"
participant "group:Group"
participant "groupLedger:Ledger"
== Act ==

":Test" -> "controller:GetPersonalAndGroupTransactionsInDateRangeController" : selectedTransactions = getPersonalAndGroupTransactions\n(person, initialDate, finalDate, groupsList)
activate "controller:GetPersonalAndGroupTransactionsInDateRangeController" #FFBBBB

"controller:GetPersonalAndGroupTransactionsInDateRangeController" -> "person:Person" : returnPersonLedgerInDateRange\n(initialDate, finalDate)
activate "person:Person" #FFBBBB
"person:Person" -> "personalLedger:Ledger" : getTransactionsInDateRange\n(initialDate, finalDate)
activate "personalLedger:Ledger" #FFBBBB

deactivate "personalLedger:Ledger" #FFBBBB
deactivate "person:Person"

"controller:GetPersonalAndGroupTransactionsInDateRangeController" -> "groupsList:GroupsList" : returnTransactionsFromAllGroupsAPersonIsIn(person, initialDate, finalDate)
activate "groupsList:GroupsList" #FFBBBB
"groupsList:GroupsList" -> "group:Group" : returnGroupLedgerInDateRange\n(initialDate, finalDate, person)
activate "group:Group" #FFBBBB
"group:Group" -> "groupLedger:Ledger" : getTransactionsInDateRange\n(initialDate, finalDate)
activate "groupLedger:Ledger" #FFBBBB

deactivate "groupLedger:Ledger" #FFBBBB
deactivate "group:Group"
deactivate "groupsList:GroupsList"

"controller:GetPersonalAndGroupTransactionsInDateRangeController" -> "controller:GetPersonalAndGroupTransactionsInDateRangeController": sort(Transaction::getDate)
deactivate "controller:GetPersonalAndGroupTransactionsInDateRangeController" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertEquals(expectedTransactions, selectedTransactions)

@enduml