@startuml

skinparam DefaultFontSize 20
create ":Test"

==Arrange==
create ":PersonalBalanceInDateRangeController"
":Test" -> ":PersonalBalanceInDateRangeController" : new PersonalBalanceInDateRangeController

participant "person1:Person"

participant "ledger:Ledger"


== Act ==

":Test" -> ":PersonalBalanceInDateRangeController" : personalBalanceInDateRange = getPersonalBalanceInDateRange\n(initialDate, finalDate,person)
activate ":PersonalBalanceInDateRangeController"  #FFBBBB

":PersonalBalanceInDateRangeController" -> "person1:Person" :getPersonalBalanceInDateRange\n(initialDate, finalDate,person)
activate "person1:Person"  #FFBBBB

"person1:Person" -> "ledger:Ledger": getBalanceInDateRange\n(initialDate, finalDate)
deactivate "person1:Person"  #FFBBBB
deactivate ":PersonalBalanceInDateRangeController"  #FFBBBB

== Assert ==

":Test" -> ":Test" : assertEquals(expectedPersonalBalanceFromDateRange, \npersonalBalanceInDateRange)


@enduml