@startuml
skinparam DefaultFontSize 20

participant ":Test"
participant "controller:US006CreatePersonAccountController"
participant "service:US006CreatePersonAccountService"
participant "personRepo:PersonRepository"
participant "accountsRepo:AccountsRepository"

== Act ==
":Test" -> "controller:US006CreatePersonAccountController" : accountCreated = createPersonAccount (service, personEmail, \n accountDenomination, accountDescription)
activate "controller:US006CreatePersonAccountController"  #FFBBBB

"controller:US006CreatePersonAccountController" -> "service:US006CreatePersonAccountService" : accountCreated = createPersonAccount\n(personEmail, accountDenomination,\n accountDescription)
activate "service:US006CreatePersonAccountService"  #FFBBBB

"service:US006CreatePersonAccountService" -> "personRepo:PersonRepository" : isOnRepo = isPersonIDOnRepository
activate "personRepo:PersonRepository"  #FFBBBB
deactivate "personRepo:PersonRepository"  #FFBBBB

"service:US006CreatePersonAccountService"  -> "accountsRepo:AccountsRepository" : accountCreated  = createPersonAccount(personID, \naccountDenomination,accountDescription)
activate "accountsRepo:AccountsRepository" #FFBBBB

"accountsRepo:AccountsRepository" -> "accountsRepo:AccountsRepository" : isNotOnRepo = isAccountIDOnRepository(accountID)
create ":Account"
"accountsRepo:AccountsRepository" -> ":Account" : new Account (personID, \n accountDenomination,\n accountDescription)

deactivate "accountsRepo:AccountsRepository" #FFBBBB
deactivate "service:US006CreatePersonAccountService"  #FFBBBB
deactivate "controller:US006CreatePersonAccountController"  #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(accountCreated)

@enduml