@startuml
skinparam DefaultFontSize 20
create ":Test"

== Arrange ==
create ":US007CreateGroupAccountController"
":Test" -> ":US007CreateGroupAccountController" : new US007Create\nGroupAccountController ()

== Act ==

":Test" -> ":US007CreateGroupAccountController" : accountCreated = createGroupAccount\n( personID, groupID, denomination, description)
activate ":US007CreateGroupAccountController"  #FFBBBB

":US007CreateGroupAccountController" -> ":US007CreateGroupAccountService" : accountCreated = createGroupAccount\n(personID, groupID, denomination, description)
activate ":US007CreateGroupAccountService"  #FFBBBB

":US007CreateGroupAccountService" -> ":GroupsRepository" : group = findGroupByID(groupID)
activate ":GroupsRepository"  #FFBBBB
deactivate ":GroupsRepository"  #FFBBBB

":US007CreateGroupAccountService" -> "group:Group" : personIsGroupAdmin = isGroupAdmin(personID)
activate "group:Group" #FFBBBB
deactivate "group:Group" #FFBBBB



":US007CreateGroupAccountService" -> ":AccountsRepository" : accountCreated = createAccount(groupID, \ndenomination,description)
activate ":AccountsRepository" #FFBBBB

":AccountsRepository" -> ":AccountsRepository" : isAccountIDOnRepository(groupID)


create ":Account"
":AccountsRepository" -> ":Account" : new Account(groupId, \ndenomination,description)

deactivate ":AccountsRepository" #FFBBBB
deactivate "group:Group" #FFBBBB
deactivate ":PersonRepository" #FFBBBB
deactivate ":GroupsRepository" #FFBBBB
deactivate ":US007CreateGroupAccountService"  #FFBBBB
deactivate ":US007CreateGroupAccountController" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(accountCreated)

@enduml