@startuml
skinparam DefaultFontSize 20

participant ":Test"
participant "controller:US007CreateGroupAccountController"
participant "service:US007CreateGroupAccountService"
participant "personRepo:PersonRepository"
participant "person:Person"
participant "groupsRepo:GroupsRepository"
participant "group:Group"
participant "accountRepo:AccountsRepository"
participant "account:Account"

== Act ==

":Test" -> "controller:US007CreateGroupAccountController" : accountCreated = createGroupAccount\n(personEmail, groupDescription, \naccountDenomination, accountDescription)
activate "controller:US007CreateGroupAccountController"  #FFBBBB

"controller:US007CreateGroupAccountController" -> "service:US007CreateGroupAccountService" : accountCreated = createGroupAccount\n(personEmail, groupDescription, \naccountDenomination, accountDescription)
activate "service:US007CreateGroupAccountService"  #FFBBBB

"service:US007CreateGroupAccountService" -> "personRepo:PersonRepository" : person = findPersonByEmail (personEmail)
activate "personRepo:PersonRepository"  #FFBBBB
deactivate "personRepo:PersonRepository"  #FFBBBB

"service:US007CreateGroupAccountService" -> "person:Person" : personID = getID ()
activate "person:Person"  #FFBBBB
deactivate "person:Person"  #FFBBBB

"service:US007CreateGroupAccountService" -> "groupsRepo:GroupsRepository" : group = findGroupByDescription (groupDescription)
activate "groupsRepo:GroupsRepository"  #FFBBBB
deactivate "groupsRepo:GroupsRepository"  #FFBBBB

"service:US007CreateGroupAccountService" -> "group:Group" : groupID = getID()
activate "group:Group" #FFBBBB
"service:US007CreateGroupAccountService" -> "group:Group" : personIsGroupAdmin = isGroupAdmin (personID)
deactivate "group:Group" #FFBBBB



"service:US007CreateGroupAccountService" -> "accountRepo:AccountsRepository" : accountCreated = createAccount(accountDenomination, accountDescription, groupID)
activate "accountRepo:AccountsRepository" #FFBBBB

"accountRepo:AccountsRepository" -> "accountRepo:AccountsRepository" : accountNotInRepository = \n isAccountIDOnRepository(accountDenomination, groupID)


create "account:Account"
"accountRepo:AccountsRepository" -> "account:Account" : new Account (accountDenomination, \n   accountDescription, groupID)
"accountRepo:AccountsRepository" -> "accountRepo:AccountsRepository" : add(account)

deactivate "accountRepo:AccountsRepository" #FFBBBB
deactivate "group:Group" #FFBBBB
deactivate "personRepo:PersonRepository" #FFBBBB
deactivate "groupsRepo:GroupsRepository" #FFBBBB
deactivate "service:US007CreateGroupAccountService"  #FFBBBB
deactivate "controller:US007CreateGroupAccountController" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(accountCreated)

@enduml