@startuml
skinparam DefaultFontSize 20

participant ":Test"

participant "controller:US005.1MemberAddCategoryToCategoryListController"

== Act ==
":Test" -> "controller:US005.1MemberAddCategoryToCategoryListController" :isCategoryCreated = addCategoryToGroupController\n(groupDescription, personEmail, categoryDenomination)
activate "controller:US005.1MemberAddCategoryToCategoryListController" #FFBBBB

"controller:US005.1MemberAddCategoryToCategoryListController"-> "service:US005.1MemberAddCategoryToCategoryListService":isCategoryCreated = addCategoryToGroup\n(groupDescription, personEmail, categoryDenomination)
activate "service:US005.1MemberAddCategoryToCategoryListService" #FFBBBB

"service:US005.1MemberAddCategoryToCategoryListService"->"groupRep:GroupRepository":group = findGroupByDescription\n(groupDescription)
activate "groupRep:GroupRepository" #FFBBBB
deactivate "groupRep:GroupRepository"

"service:US005.1MemberAddCategoryToCategoryListService"->"personRep:PersonRepository": person = findPersonByEmail(personEmail)
activate "personRep:PersonRepository" #FFBBBB
deactivate "personRep:PersonRepository"

"service:US005.1MemberAddCategoryToCategoryListService"->"person:Person": personID = getID()
activate "person:Person" #FFBBBB
deactivate "person:Person"

"service:US005.1MemberAddCategoryToCategoryListService"->"group:Group": validateAdmin = isGroupAdmin(personID)
activate "group:Group" #FFBBBB
deactivate "group:Group"

"service:US005.1MemberAddCategoryToCategoryListService"->"group:Group": groupID = getID()
activate "group:Group" #FFBBBB
deactivate "group:Group"

"service:US005.1MemberAddCategoryToCategoryListService"->"categoryRep:CatRepository":isCategoryCreated = createCategory(categoryDenomination, groupID)
activate "categoryRep:CatRepository" #FFBBBB

create "category:Category"
"categoryRep:CatRepository"->"category:Category":new Category\n(categoryDenomination, groupID)
"categoryRep:CatRepository"->"categoryRep:CatRepository": add(category)

deactivate "categoryRep:CatRepository"
deactivate "service:US005.1MemberAddCategoryToCategoryListService"
deactivate "controller:US005.1MemberAddCategoryToCategoryListController"


== Assert ==
":Test" -> ":Test" : assertTrue(isCategoryCreated)
@enduml