@startuml
skinparam DefaultFontSize 20
create ":Test"

== Arrange ==

create "person1:Person"
":Test" -> "person1:Person" : new Person (name, birthDate, birthPlace, homeAddress, mother, father)
activate "person1:Person" #FFBBBB

create "group1:Group"
"group1:Group" <- "person1:Person" : new Group
deactivate "person1:Person" #FFBBBB

== Act ==
"person1:Person" -> "group1:Group" : addMember(person1)
activate "group1:Group" #FFBBBB
activate "person1:Person" #FFBBBB

"group1:Group" --> "person1:Person": memberAdded
deactivate  "group1:Group" #FFBBBB

"person1:Person" --> ":Test" : memberAdded
deactivate  "person1:Person" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(memberAdded)

@enduml