@startuml
skinparam DefaultFontSize 20
participant ":Test"
create ":US004GetFamilyGroupsController"

":Test" -> ":US004GetFamilyGroupsController" : new US004GetFamilyGroupsController()
":Test" -> ":US004GetFamilyGroupsController" : groups = getFamilyGroups(service, groupsRepository)
activate ":US004GetFamilyGroupsController" #FFBBBB

participant "service:US004GetFamilyGroupsService"
":US004GetFamilyGroupsController" -> "service:US004GetFamilyGroupsService" : groups = getFamilyGroups(groupsRepository)
activate "service:US004GetFamilyGroupsService" #FFBBBB

participant ":GroupRepository"
"service:US004GetFamilyGroupsService" -> ":GroupRepository" : families = returnOnlyFamilies()
activate ":GroupRepository" #FFBBBB

participant ":Group"
":GroupRepository" -> ":Group" : family = isFamily()
deactivate ":US004GetFamilyGroupsController"
deactivate "service:US004GetFamilyGroupsService"
deactivate ":GroupRepository"


":Test" -> ":Test" : assertEquals(expected, groups)


@enduml
