@startuml
skinparam DefaultFontSize 20

participant ":Test"

participant "controller:US001AreSiblingsController"
participant "service:US001AreSiblingsService"
participant "personRepo:PersonRepository"
participant "person1:Person"

== Act ==

":Test" -> "controller:US001AreSiblingsController" : siblings = AreSiblings(personEmail1, personEmail2)
activate "controller:US001AreSiblingsController"  #FFBBBB

"controller:US001AreSiblingsController"-> "service:US001AreSiblingsService" : siblings = AreSiblings\n(personEmail1, personEmail2)
activate "service:US001AreSiblingsService"  #FFBBBB

"service:US001AreSiblingsService" -> "personRepo:PersonRepository" : person1: findPersonByEmail(personEmail1)
activate "personRepo:PersonRepository" #FFBBBB

"service:US001AreSiblingsService" -> "personRepo:PersonRepository" : person2: findPersonByEmail(personEmail2)

deactivate "personRepo:PersonRepository" #FFBBBB

"service:US001AreSiblingsService" -> "person1:Person" : validSibling = isSibling(person2)
activate "person1:Person"  #FFBBBB

"person1:Person" -> "person1:Person" :  personExistsOnSiblingsList(person2)
"person1:Person" -> "person1:Person" :  checkSameFather(person2)
"person1:Person" -> "person1:Person" :  checkSameMother(person2)

"person1:Person" --> "service:US001AreSiblingsService" : validSibling
deactivate "person1:Person"

"service:US001AreSiblingsService"--> "controller:US001AreSiblingsController" : siblings
deactivate "service:US001AreSiblingsService"

"controller:US001AreSiblingsController" --> ":Test" : siblings
deactivate "controller:US001AreSiblingsController"

== Assert ==

":Test" -> ":Test" : assertTrue(siblings)

@enduml