@startuml
skinparam DefaultFontSize 20

== Act ==

":Test" -> "controller:US003AddMemberToGroupController" : memberAdded = addMemberToGroup \n (personEmail, groupDescription)
activate "controller:US003AddMemberToGroupController" #FFBBBB

participant "service:US003AddMemberToGroupService"
"controller:US003AddMemberToGroupController" -> "service:US003AddMemberToGroupService" : memberAdded = addMemberToGroup\n (personEmail, groupDescription)
activate "service:US003AddMemberToGroupService" #FFBBBB

participant "personRepo:PersonsRepository"
"service:US003AddMemberToGroupService" -> "personRepo:PersonsRepository" : person = findPersonByEmail (personEmail)
activate "personRepo:PersonsRepository" #FFBBBB
deactivate "personRepo:PersonsRepository" #FFBBBB

participant "groupsRepo:GroupsRepository"
"service:US003AddMemberToGroupService" -> "groupsRepo:GroupsRepository" : group = findGroupByDescription (groupDescription)
activate "groupsRepo:GroupsRepository" #FFBBBB
deactivate "groupsRepo:GroupsRepository" #FFBBBB

participant "group:Group"
"service:US003AddMemberToGroupService" -> "group:Group" : memberAdded = addMemberToGroup (person)
activate "group:Group" #FFBBBB
deactivate "group:Group" #FFBBBB
deactivate "controller:US003AddMemberToGroupController" #FFBBBB
deactivate "service:US003AddMemberToGroupService" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(memberAdded)

@enduml