pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out...'
                git url: 'https://martalribeiro@bitbucket.org/martalribeiro/devops_g2_maven.git/'
            }
        }
        stage('Assemble') {
            steps {
                dir('personalFinanceManagement') {
                    echo 'Building...'
                    sh 'chmod +x mvnw'
                    sh './mvnw package -Dmaven.test.skip=true '
                }
            }
        }
         stage('Test') {
            steps {
                dir('personalFinanceManagement') {
                    echo 'Testing...'
                    sh 'chmod +x mvnw'
                    sh './mvnw surefire-report:report '
                    archiveArtifacts 'target/site/*.html'
                }
                dir('personalFinanceManagement') {
                    echo 'Generating code coverage...'
                    sh 'chmod +x mvnw'
                    sh './mvnw verify'
                    archiveArtifacts 'target/site/jacoco/index.html'
                }
            }
        }
        stage ('Javadoc'){
            steps {
                dir('personalFinanceManagement') {
                    echo 'Generating javadocs...'
                    sh 'chmod +x mvnw'
                    sh './mvnw javadoc:javadoc'
                    publishHTML ([
                                reportName: 'Javadoc',
                                reportDir: 'target/site/apidocs/',
                                reportFiles: 'index.html',
                                keepAll: true,
                                alwaysLinkToLastBuild: false,
                                allowMissing: true
                    ])
                }
            }
        }
        stage('Archiving') {
            steps {
                dir('personalFinanceManagement') {
                    sh 'dir'
                    echo 'Archiving...'
                    archiveArtifacts 'target/*.war'
                }
            }
        }
        stage('Docker Image') {
             steps {
                dir ('scripts/web') {
                    script {
                        webAppImage = docker.build("raquelquerido/devops_g2_gradle:${env.BUILD_ID}")
                    }
                }
                dir ('scripts/db') {
                    script {
                        dbImage = docker.build("raquelquerido/devops_g2_gradle:${env.BUILD_ID}")
                    }
                }
            }
        }
        stage('Publish Image') {
            steps {
                script{
                    sh 'docker login -u="raquelquerido" -p="devops1313"'
                    webAppImage.push()
                    dbImage.push()
                }
            }
        }

       stage('Ansible Deploy') {
            steps {
                dir('scripts') {
                        ansiblePlaybook (
                           become: true,
                           disableHostKeyChecking: true,
                           inventory: 'hosts',
                           playbook: 'playbook1.yml'
                   )
               }
            }
        }
    }
}