pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out...'
                git url: 'https://gabrielPereira12@bitbucket.org/martalribeiro/devops_g2_maven.git/'
            }
        }
        stage('Assemble') { //  qual o objectivo desta fase?
            steps {
                dir('personalFinanceManagement') {
                    echo 'Building...'
                    sh './mvnw package -Dmaven.test.skip=true '
                }
            }
        }
        stage('Test') {
            steps {
                dir('personalFinanceManagement') {
                    echo 'Testing...'
                    sh './mvnw surefire-report:report '
                    archiveArtifacts 'target/site/*.html'
                }
                dir('personalFinanceManagement') {
                    echo 'Generating code coverage...'
                    sh './mvnw verify'
                    archiveArtifacts 'target/site/jacoco/index.html'
                }
            }
        }
        stage ('Javadoc'){
            steps {
                dir('personalFinanceManagement') {
                    echo 'Generating javadocs...'
                    sh './mvnw javadoc:javadoc'
                    publishHTML ([
                                reportName: 'Javadoc',
                                reportDir: 'target/site/apidocs/',
                                reportFiles: 'index.html',
                                keepAll: true,
                                alwaysLinkToLastBuild: false,
                                allowMissing: true
                    ])
                }
            }
        }
        stage('Archiving') {
            steps {
                dir('personalFinanceManagement') {
                    sh 'dir'
                    echo 'Archiving...'
                    archiveArtifacts 'target/*.war'
                }
            }
        }
        /*
        stage('Docker Image') {
             steps {
                dir ('/Dockerfile1') {
                    script {
                        webAppImage = docker.build("gabriel1191765/devops_g2_maven:${env.BUILD_ID}")
                    }
                }
                dir ('/Dockerfile2') {
                    script {
                        dbImage = docker.build("gabriel1191765/devops_g2_maven:${env.BUILD_ID}")
                    }
                }
            }
        }
        stage('Publish Image') {
            steps {
                script{
                    sh 'docker login -u="gabriel1191765" -p="gabriel2636"'
                    webAppImage.push()
                    dbImage.push()
                }
            }
        }
        */

        /*
        stage ('Ansible') {
            steps {
                ansiblePlaybook (inventory: 'hosts', playbook: 'playbook1.yml')
            }
        }
        */
    }
}