---
- hosts: otherservers
  become: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: remove apache
      apt: name=apache2 state=absent
    - name: install jdk
      apt: name=openjdk-8-jdk-headless state=present

- hosts: host2
  become: yes
  tasks:
    - name: install postgresql
      apt: name=postgresql update_cache=true state=present
    - name: install postgresql-contrib
      apt: name=postgresql-contrib state=present
    - name: install libpq
      apt: name=libpq-dev state=present
    - name: install python-psycopg2
      apt: name=python-psycopg2 state=present
    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes
    - name: Configure PostgreSQL. Set listen_addresses.
      lineinfile:
        dest: /etc/postgresql/9.5/main/postgresql.conf
        regexp: "listen_addresses ="
        line: "listen_addresses = '*'"
        state: present
      become: true
      notify: restart postgresql
    - name: Configure PostgreSQL. Change postgres pg hba access.
      postgresql_pg_hba:
        dest: /etc/postgresql/9.5/main/pg_hba.conf
        contype: host
        users: postgres
        source: all
        databases: postgres
        method: md5
        create: true
      become: true
      notify: restart postgresql
    - name: create postgresql user
      become: yes
      postgresql_user:
        user: "postgres"
        password: "postgres"
        role_attr_flags: "CREATEDB,NOSUPERUSER"
      become_user: postgres
      notify: restart postgresql
    - name: create postgresql db
      postgresql_db:
        name: "postgres"
        state: present
      become: true
      become_user: postgres
      notify: restart postgresql  

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

- hosts: host1
  become: yes
  tasks:
    - name: install git
      apt: name=git state=present 
    - name: install nodejs
      shell: apt-get install nodejs -y
    - name: install nodejs
      shell: apt-get install npm -y
    - name: create symbolic link
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link
    - name: clone repository
      git:
        repo: https://1191780@bitbucket.org/martalribeiro/postgres.git
        dest: /home/vagrant/devops_g2_maven
    - name: give permission to execute maven wrapper
      file:
        path: /home/vagrant/devops_g2_maven/personalFinanceManagement/mvnw
        mode: "+rwx"
    - name: maven build
      shell:
        cmd: ./mvnw package -Dmaven.test.skip=true
        chdir: /home/vagrant/devops_g2_maven/personalFinanceManagement
    - name: give permission to execute war file
      file:
        path: /home/vagrant/devops_g2_maven/personalFinanceManagement/target/devOpsProject-1.0-SNAPSHOT.war
        mode: "+rwx"
    - name: deploy the war file
      shell:
        cmd: java -jar devOpsProject-1.0-SNAPSHOT.war
        chdir: /home/vagrant/devops_g2_maven/personalFinanceManagement/target

