---
- hosts: otherservers
  become: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: remove apache
      apt: name=apache2 state=absent
    - name: install jdk
      apt: name=openjdk-8-jdk-headless state=present

- hosts: host2
  become: yes
  tasks:
    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes


- hosts: host1
  become: yes
  tasks:
    - name: install git
      apt: name=git state=present 
    - name: install nodejs
      shell: apt-get install nodejs -y
    - name: install npm
      shell: apt-get install npm -y
    - name: create symbolic link
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link
    - name: clean existent repository
      shell: rm -r -f /home/vagrant/devops_g2_maven
    - name: clone repository
      git:
        repo: https://martalribeiro@bitbucket.org/martalribeiro/devops_g2_maven.git
        dest: /home/vagrant/devops_g2_maven
    - name: give permission to execute maven wrapper
      file:
        path: /home/vagrant/devops_g2_maven/personalFinanceManagement/mvnw
        mode: 0755
    - name: maven build
      shell:
        cmd: ./mvnw package -Dmaven.test.skip=true
        chdir: /home/vagrant/devops_g2_maven/personalFinanceManagement
    - name: give permission to execute war file
      file:
        path: /home/vagrant/devops_g2_maven/personalFinanceManagement/target/devOpsProject-1.0-SNAPSHOT.war
        mode: 0755
    - name: deploy the war file
      shell: java -jar /home/vagrant/devops_g2_maven/personalFinanceManagement/target/devOpsProject-1.0-SNAPSHOT.war
      async: 2592000
      poll: 0
