---
- hosts: otherservers
  become: yes
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: remove apache
      apt: name=apache2 state=absent
    - name: install jdk
      apt: name=openjdk-8-jdk-headless state=present

- hosts: host2
  become: yes
  tasks:
    - name: install postgresql
      apt: name=postgresql update_cache=true state=present
    - name: install postgresql-contrib
      apt: name=postgresql-contrib state=present
    - name: install libpq
      apt: name=libpq-dev state=present
    - name: install python-psycopg2
      apt: name=python-psycopg2 state=present
    # - name: start postgresql server
    #   shell: systemctl start postgresql

- hosts: host1
  become: yes
  tasks:
    - name: install tomcat8
      apt: name=tomcat8 state=present
    - name: install tomcat8admin
      apt: name=tomcat8-admin state=present
    - name: install git
      apt: name=git state=present 
    - name: install nodejs
      shell: apt-get install nodejs -y
    - name: install nodejs
      shell: apt-get install npm -y
    - name: create symbolic link
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link
    - name: clone repository
      git:
        repo: https://1191780@bitbucket.org/martalribeiro/postgres.git
        dest: /home/vagrant/devops_g2_maven
    - name: give permission to execute maven wrapper
      file:
        path: /home/vagrant/devops_g2_maven/personalFinanceManagement/mvnw
        mode: "+rwx"
    - name: maven build
      shell:
        cmd: ./mvnw spring-boot:run
        chdir: /home/vagrant/devops_g2_maven/personalFinanceManagement

