@startuml

skinparam DefaultFontSize 20

participant ":Test"
note left of ":Test" #powderblue
	Arrange
end note

create ":PersonLedgerInDateRangeController"
":Test" -> ":PersonLedgerInDateRangeController" : new PersonLedger\nInDateRangeController()

create "person1:Person"
":Test" -> "person1:Person" : new Person (name, birthDate, birthPlace, homeAddress, mother, father)
activate "person1:Person" #FFBBBB

create "ledger1:Ledger"
"person1:Person" -> "ledger1:Ledger" : new Ledger()
deactivate "person1:Person" #FFBBBB
activate "ledger1:Ledger" #FFBBBB

create ":Transaction"
"ledger1:Ledger" -> ":Transaction" : new Transaction(amount, description, \ncat, accountFrom, accountTo, type)
deactivate "ledger1:Ledger" #FFBBBB

note left of ":Test" #powderblue
	Act
end note

":Test" -> ":PersonLedgerInDateRangeController" : returnedTransactions = returnPersonLedger\nInDateRange(initialDate, finalDate, person1)
activate ":PersonLedgerInDateRangeController" #FFBBBB

":PersonLedgerInDateRangeController" -> "person1:Person" : returnPersonLedgerInDateRange\n(initialDate, finalDate)
activate "person1:Person" #FFBBBB

"person1:Person" -> "ledger1:Ledger" : getTransactionsInDateRange\n(initialDate, finalDate)
activate "ledger1:Ledger" #FFBBBB

deactivate "ledger1:Ledger" #FFBBBB
deactivate "person1:Person" #FFBBBB
deactivate ":PersonLedgerInDateRangeController" #FFBBBB

note left of ":Test" #powderblue
	Assert
end note

":Test" -> ":Test" : assertTrue(returnedTransactions)

@enduml