@startuml
create ":Test"

==Arrange==
create "createTransaction:Controller"
create "group1:Group"
create "catList: CategoryList"
create "acList:AccountsList"
create "ledger:Ledger"

create "amount:MonetaryValue"
":Test" -> "amount:MonetaryValue" : create (amount, currency)

== Act ==

":Test" -> "createTransaction:Controller" : createGroupTransaction (amount, description, \ncat, accountFrom, accountTo, type)
activate "createTransaction:Controller"  #FFBBBB

"createTransaction:Controller" -> "group1:Group" : createGroupTransaction (amount, description, \ncat, accountFrom, accountTo, type)
activate "group1:Group"  #FFBBBB

"group1:Group" -> "ledger:Ledger" : addTransactionToLedger(amount, description, cat, accountFrom, accountTo, type)
activate "ledger:Ledger"  #FFBBBB

create "transaction:Transaction"
"ledger:Ledger" -> "transaction:Transaction" : create (amount, description, cat, accountFrom, accountTo, type)

"ledger:Ledger" -> "ledger:Ledger": add
deactivate "ledger:Ledger"  #FFBBBB
deactivate "group1:Group"  #FFBBBB
deactivate "createTransaction:Controller"  #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(TransactionCreated)

@enduml