@startuml
skinparam DefaultFontSize 20
participant ":Test"
== Arrange ==

create "controller:GetPersonalAndGroupTransactionsInDateRangeController"
":Test" -> "controller:GetPersonalAndGroupTransactionsInDateRangeController" : create()

participant "person:Person"
participant "personalLedger:Ledger"
participant "groupsList:GroupsList"
participant "group:Group"
participant "groupLedger:Ledger"
participant "transaction:Transaction"

== Act ==

":Test" -> "controller:GetPersonalAndGroupTransactionsInDateRangeController" : selectedTransactions = getPersonalAndGroupTransactions\n(person, initialDate, finalDate, groupsList)
activate "controller:GetPersonalAndGroupTransactionsInDateRangeController" #FFBBBB

"controller:GetPersonalAndGroupTransactionsInDateRangeController" -> "person:Person" : returnPersonLedgerInDateRange\n(initialDate, finalDate)
activate "person:Person" #FFBBBB
"person:Person" -> "personalLedger:Ledger" : getTransactionsInDateRange\n(initialDate, finalDate)
activate "personalLedger:Ledger" #FFBBBB
"personalLedger:Ledger" --> "person:Person" : personalTransactions
deactivate "personalLedger:Ledger" #FFBBBB
"person:Person" --> "controller:GetPersonalAndGroupTransactionsInDateRangeController" : personalTransactions
deactivate "person:Person"

"controller:GetPersonalAndGroupTransactionsInDateRangeController" -> "groupsList:GroupsList" : returnTransactionsFromAllGroupsAPersonIsIn(person, initialDate, finalDate)
activate "groupsList:GroupsList" #FFBBBB
"groupsList:GroupsList" -> "group:Group" : returnGroupLedgerInDateRange\n(initialDate, finalDate, person)
activate "group:Group" #FFBBBB
"group:Group" -> "groupLedger:Ledger" : getTransactionsInDateRange\n(initialDate, finalDate)
activate "groupLedger:Ledger" #FFBBBB
"groupLedger:Ledger" --> "group:Group" : groupTransactions
deactivate "groupLedger:Ledger" #FFBBBB
"group:Group" --> "groupsList:GroupsList" : groupTransactions
deactivate "group:Group"
"groupsList:GroupsList" --> "controller:GetPersonalAndGroupTransactionsInDateRangeController" : groupTransactions
deactivate "groupsList:GroupsList"
"controller:GetPersonalAndGroupTransactionsInDateRangeController" -> "controller:GetPersonalAndGroupTransactionsInDateRangeController": sort(Transaction::getDate)
"controller:GetPersonalAndGroupTransactionsInDateRangeController" --> ":Test" : selectedTransactions
deactivate "controller:GetPersonalAndGroupTransactionsInDateRangeController" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertEquals(expectedTransactions, \n                    selectedTransactions)

@enduml