@startuml
create ":Test"

== Arrange ==
create "US017:Controller"

create "person:Person"
":Test" -> "person:Person" : create(name, birthDate, birthPlace, homeAddress, mother, father)
activate "person:Person" #FFBBBB

create "ledger:Ledger"
"person:Person" -> "ledger:Ledger" : create()
deactivate "person:Person"
":Test" -> "person:Person" : createTransaction(amount, description, date, category, \n                             accountFrom, accountTo, type)
activate "person:Person" #FFBBBB

"person:Person" -> "ledger:Ledger" : addTransactionToLedger(amount, description, date, category, \n                                         accountFrom, accountTo, type)
deactivate "person:Person" #FFBBBB
activate "ledger:Ledger" #FFBBBB
create "transaction:Transaction"
"ledger:Ledger" -> "transaction:Transaction" : create(amount, description, date, category, \n             accountFrom, accountTo, type)
deactivate "person:Person"
deactivate "ledger:Ledger"

== Act ==

":Test" -> "US017:Controller" : getPersonalBalanceInDateRange(person, initialDate, finalDate)
activate "US017:Controller" #FFBBBB
"US017:Controller" -> "person:Person": getPersonalBalanceInDateRange(initialDate, finalDate)
activate "person:Person" #FFBBBB
"person:Person" -> "ledger:Ledger": getBalanceInDateRange(initialDate, finalDate)
activate "ledger:Ledger" #FFBBBB
"ledger:Ledger" -> "person:Person" : finalBalance
deactivate "ledger:Ledger"
"person:Person" -> "US017:Controller" : finalBalance
deactivate "person:Person"
"US017:Controller" -> ":Test" : finalBalance
deactivate "US017:Controller"

== Assert ==

":Test" -> ":Test" : assertEquals(expectedPersonalBalanceFromDateRange, \n                        personalBalanceFromDateRange)

@enduml