@startuml

create ":Test"

== Arrange ==

create "person1:Person"
":Test" -> "person1:Person" : new Person
activate "person1:Person" #FFBBBB

create "category1:Category"
create "categoryList1:CategoryList"

"person1:Person" -> "categoryList1:CategoryList" : new categoryListL
deactivate "person1:Person" #FFBBBB

== Act ==

":Test" -> "person1:Person" : createCategory(description)
activate "person1:Person" #FFBBBB

create "category1:Category"
"person1:Person" -> "category1:Category" : new Category

"person1:Person" -> "categoryList1:CategoryList" : addCategoryToCategoryList(category1)
activate "categoryList1:CategoryList" #FFBBBB

"categoryList1:CategoryList" --> "person1:Person" : categoryCreatedAndAdded
deactivate "categoryList1:CategoryList" #FFBBBB

"person1:Person" --> ":Test" : categoryCreatedAndAdded
deactivate "person1:Person" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(categoryAddedToCategoryList)

@enduml

