@startuml
skinparam DefaultFontSize 20
participant ":Test"

== Arrange ==

create "controller:PersonalScheduleController"
":Test" -> "controller:PersonalScheduleController" : create()

participant "person:Person"
participant "scheduledTasksList:ScheduledTasksList"
participant "personalLedger:Ledger"

== Act ==

":Test" -> "controller:PersonalScheduleController" : scheduleTransaction = schedulePersonalTransaction\n(person, periodicity, amount, description, date, \ncategory, accountFrom, accountTo, type)
activate "controller:PersonalScheduleController" #FFBBBB
"controller:PersonalScheduleController" -> "person:Person" : scheduleNewTransaction\n(periodicity, amount, description, date, \ncategory, accountFrom, accountTo, type)
activate "person:Person" #FFBBBB
"person:Person" -> "scheduledTasksList:ScheduledTasksList" : addNewSchedule\n(this, periodicity, amount, \ndescription, date,
activate "scheduledTasksList:ScheduledTasksList" #FFBBBB
create "schedule:Schedule"
"scheduledTasksList:ScheduledTasksList" -> "schedule:Schedule" : create(person, periodicity, amount, \ndescription, date, category, \naccountFrom, accountTo, type)
activate "schedule:Schedule" #FFBBBB
create "scheduledTransactionTask:TransactionTask"
deactivate "scheduledTasksList:ScheduledTasksList"
"schedule:Schedule" -> "scheduledTransactionTask:TransactionTask" : create(person, amount, \ndescription, date, category, \naccountFrom, accountTo, type)
deactivate "schedule:Schedule"
activate "scheduledTransactionTask:TransactionTask" #FFBBBB
"scheduledTransactionTask:TransactionTask" -> "person:Person" : createTransaction(amount, description, localDate, \ncategory, accountFrom, accountTo, type)
deactivate "scheduledTransactionTask:TransactionTask"

":Test" -> "controller:PersonalScheduleController" : ledgerSize = ledgerSize(person)
"controller:PersonalScheduleController" -> "person:Person" : ledgerSize = ledgerSize()
"person:Person" -> "personalLedger:Ledger" : ledgerSize = getLedgerSize()
activate "personalLedger:Ledger" #FFBBBB
deactivate "person:Person"
deactivate "controller:PersonalScheduleController"
deactivate "personalLedger:Ledger"

== Assert ==

":Test" -> ":Test" : assertTrue(scheduleTransaction && ledgerSize)


@enduml