@startuml
create ":Test"

==Arrange==

create "US010:controller"

create "onePerson:Person"

create "oneGroup:Group"

create "ledger:Ledger"

"oneGroup:Group" -> "ledger:Ledger" : create ()
"oneGroup:Group" -> "ledger:Ledger" : addTransactionToLedger(amount, description, cat, accountFrom, accountTo, type)
create "transaction:Transaction"


"ledger:Ledger" -> "transaction:Transaction" : create (amount, description, cat, accountFrom, accountTo, type)
"ledger:Ledger" -> "ledger:Ledger" : add


"oneGroup:Group" -> "oneGroup:Group" : addMember (onePerson)


== Act ==

":Test" -> "US010:controller" : getOneAccountMovementsFromGroup\n(oneAccount, dateFrom, dateTo, onePerson)

"US010:controller" -> "oneGroup:Group" : getOneAccountMovementsFromGroup\n(oneAccount, dateFrom, dateTo, onePerson)

"oneGroup:Group" -> "ledger:Ledger" : getOneAccountMovementsFromGroup\n(oneAccount, dateFrom, dateTo, onePerson)

== Assert ==

":Test" -> ":Test" : assertEquals(expected, real)

@enduml