---------+@startuml

create ":Test"

== Arrange ==

create "group1:Group"
":Test" -> "group1:Group" : new Group (description)
activate "group1:Group" #FFBBBB

create "account1:Account"
create "accountList1:AccountsList"
"group1:Group" -> "accountList1:AccountsList" : new AccountsList
deactivate "group1:Group" #FFBBBB

== Act ==

":Test" -> "group1:Group" : createGroupAccount(denomination, description)
activate "group1:Group" #FFBBBB

create "account1:Account"
"group1:Group" -> "account1:Account" : new Account(denomination,description)

"group1:Group" -> "accountList1:AccountsList" : addAccountToGroupAccountsList(account1)
activate "accountList1:AccountsList" #FFBBBB

"accountList1:AccountsList" --> "group1:Group" : accountCreatedAndAdded
deactivate "accountList1:AccountsList" #FFBBBB

"group1:Group" --> ":Test" : accountCreatedAndAdded
deactivate "group1:Group" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(accountCreatedAndAdded)

@enduml