@startuml

skinparam DefaultFontSize 20

create ":Test"

==Arrange==
create "groupTransaction:MemberCreatesGroupTransactionController"
":Test" -> "groupTransaction:MemberCreatesGroupTransactionController" : new MemberCreatesGroupTransactionController

participant "group1:Group"
participant "catList: CategoryList"
participant "acList:AccountsList"
participant "ledger:Ledger"

== Act ==

":Test" -> "groupTransaction:MemberCreatesGroupTransactionController" : transactionCreated = memberCreatesAGroupTransaction (amount, description, \ncat, accountFrom, accountTo, type, group1, transactionCreator)
activate "groupTransaction:MemberCreatesGroupTransactionController"  #FFBBBB

"groupTransaction:MemberCreatesGroupTransactionController" -> "group1:Group" : createGroupTransaction (amount, description, \ncat, accountFrom, accountTo, type)
activate "group1:Group"  #FFBBBB

"group1:Group" -> "ledger:Ledger" : addTransactionToLedger(amount, description, \ncat, accountFrom, accountTo, type)
activate "ledger:Ledger"  #FFBBBB

create "transaction:Transaction"
"ledger:Ledger" -> "transaction:Transaction" : new Transaction (amount, description, cat, accountFrom, accountTo, type)
activate "transaction:Transaction"  #FFBBBB

"ledger:Ledger" -> "transaction:Transaction" : isAValidTransaction(amount, description, cat, accountFrom, accountTo, type)
deactivate "transaction:Transaction"  #FFBBBB

"ledger:Ledger" -> "ledger:Ledger": add(Transaction)
deactivate "ledger:Ledger"  #FFBBBB

"group1:Group" -> "group1:Group" : isTransactionInsideTheGroupLedger(Transaction)

deactivate "group1:Group"  #FFBBBB
deactivate "groupTransaction:MemberCreatesGroupTransactionController" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(transactionCreated)

@enduml