@startuml
create ":Test"

==Arrange==
create ":US0012Controller"
create "group1:Group"


create "person1:Person"
":Test" -> "person1:Person" : create(name, birthDate, birthPlace, homeAddress, mother, father)

create "ledger1:Ledger"
"person1:Person" -> "ledger1:Ledger" : create()

== Act ==

":Test" -> ":US0012Controller" : ArrayListTransaction=getTransactionInDateRange(inicialDate,finalDate)
activate ":US0012Controller"  #FFBBBB

":US0012Controller" -> "group1:Group" : ArrayListTransaction=getTransactionInDateRange(inicialDate,finalDate)
activate "group1:Group"  #FFBBBB

"group1:Group" -> "ledger1:Ledger" : ArrayListTransaction=getTransactionInDateRange(inicialDate,finalDate)
activate "ledger1:Ledger"  #FFBBBB



deactivate "group1:Group"  #FFBBBB
deactivate ":US0012Controller"  #FFBBBB

== Assert ==

":Test" -> ":Test" : assertEquals(expectedArrayListTransaction,ArrayListTransaction)

@enduml