@startuml

create ":Test"

note left of ":Test" #powderblue
	Arrange
end note

create "group1:Group"
":Test" -> "group1:Group" : new Group (description)
activate "group1:Group" #FFBBBB

create "accountList1:AccountsList"
"group1:Group" -> "accountList1:AccountsList" : new AccountList
deactivate "group1:Group" #FFBBBB

note left of ":Test" #powderblue
	Act
end note

":Test" -> "group1:Group" : createGroupAccount(denomination, description)
activate "group1:Group" #FFBBBB

"group1:Group" -> "accountList1:AccountsList" : addAccountToGroupAccountsList(denomination, description)
activate "accountList1:AccountsList" #FFBBBB

create "account1:Account"
"accountList1:AccountsList" -> "account1:Account" : new Account(denomination,description)

"accountList1:AccountsList" --> "group1:Group" : accountCreatedAndAdded
deactivate "accountList1:AccountsList" #FFBBBB

"group1:Group" --> ":Test" : accountCreatedAndAdded
deactivate "group1:Group" #FFBBBB

note left of ":Test" #powderblue
	Assert
end note

":Test" -> ":Test" : assertTrue(accountCreatedAndAdded)

@enduml