@startuml

create ":Test"
create ":Controller"

== Arrange ==
create "groupList1:GroupsList"
":Test" -> "groupList1:GroupsList" : new GroupList()

== Act ==
":Test" -> ":Controller" : createGroup(groupDescription, groupDescription)
":Controller" -> "groupList1:GroupsList" : createGroup(groupDescription, groupCreator)

create "group1:Group"
"groupList1:GroupsList" -> "group1:Group": newGroup(groupDescription)
"group1:Group" ->"group1:Group": addMember(groupCreator)
"group1:Group" ->"groupList1:GroupsList": groupCreatedAndAddedToGroupsListWithOneAdminstrator
"groupList1:GroupsList" -> ":Controller": groupCreatedAndAddedToGroupsListWithOneAdminstrator
":Controller" -> ":Test": groupCreatedAndAddedToGroupsListWithOneAdminstrator

== Assert ==

":Test" -> ":Test" : assertTrue(groupCreatedAndAddedToGroupsListWithOneAdminstrator)

@enduml