@startuml
create ":Test"

==Arrange==
create ":US0012Controller"
create "group1:Group"


create "transaction:Transaction"
":Test" -> "transaction:Transaction" :

== Act ==

":Test" -> ":US0012Controller" : setTransaction=getTransaction(inicialDate,finalDate)
activate ":US0012Controller"  #FFBBBB

":US0012Controller" -> "group1:Group" : setTransaction=getTransaction(inicialDate,finalDate)
activate "group1:Group"  #FFBBBB

"group1:Group" -> "ledger1:Ledger" : ArrayListTransaction=getTransaction(inicialDate,finalDateDate)
activate "ledger1:Ledger"  #FFBBBB



deactivate "group1:Group"  #FFBBBB
deactivate ":US0012Controller"  #FFBBBB

== Assert ==

":Test" -> ":Test" : assertEquals

@enduml