@startuml

skinparam DefaultFontSize 20

create ":Test"

==Arrange==

create ":GetTheTransactionsOfAnAccountInDateRangeController"
":Test" -> ":GetTheTransactionsOfAnAccountInDateRangeController" : new

participant "person1:Person"

participant "ledger:Ledger"
deactivate "person1:Person" #FFBBBB
deactivate ":GetTransactionsOfAnAccountInDateRangeController" #FFBBBB

== Act ==

":Test" -> ":GetTheTransactionsOfAnAccountInDateRangeController" : getOneAccountTransactionsFromUser\n(account, initialDate, finalDate, person)
activate ":GetTheTransactionsOfAnAccountInDateRangeController" #FFBBBB
":GetTheTransactionsOfAnAccountInDateRangeController" -> "person1:Person" : getOneAccountTransactionsFromUser\n(account, initialDate, finalDate)
activate "person1:Person" #FFBBBB


"person1:Person" -> "ledger:Ledger" : getTransactionsInDateRange(initialDate, finalDate)
activate "ledger:Ledger" #FFBBBB
"ledger:Ledger" --> "person1:Person" : listOfTransactionsFromPeriod

"person1:Person" -> "ledger:Ledger" : getTransactionsFromOneAccount (account, listOfTransactionsFromPeriod)
"ledger:Ledger" --> "person1:Person" : listOfTransactions
deactivate "ledger:Ledger" #FFBBBB
"person1:Person" --> ":GetTheTransactionsOfAnAccountInDateRangeController" : listOfTransactions
deactivate "person1:Person" #FFBBBB
":GetTransactionsOfAnAccountInDateRangeController" --> ":Test" : listOfTransactions
deactivate ":GetTheTransactionsOfAnAccountInDateRangeController" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertEquals(expectedTransactions, listOfTransactions)

@enduml