@startuml
create ":Test"

==Arrange==

create "person1:Person"
":Test" -> "person1:Person" : new Person (name, birthDate, birthPlace, homeAddress, mother, father)
activate "person1:Person" #FFBBBB

create "accountList1:AccountsList"
"person1:Person" -> "accountList1:AccountsList" : new AccountList
deactivate "person1:Person" #FFBBBB


==Act==
":Test" -> "person1:Person" : createAccount(denomination, description)
activate "person1:Person" #FFBBBB

"person1:Person" -> "accountList1:AccountsList" : addAccountToAccountsList(denomination, description)
activate "accountList1:AccountsList" #FFBBBB

create "account1:Account"
"accountList1:AccountsList" -> "account1:Account" : new Account(denomination,description)

"accountList1:AccountsList" --> "person1:Person" : accountCreatedAndAdded
deactivate "accountList1:AccountsList" #FFBBBB

"person1:Person" --> ":Test" : accountCreatedAndAdded
deactivate "person1:Person" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(createAccount)
@enduml