@startuml
create ":Test"

==Arrange==

create "controller:MemberGetsTheMovementsInAgivenPeriodController"
":Test" -> "controller:MemberGetsTheMovementsInAgivenPeriodController" : Create ()
create "onePerson:Person"
create "oneGroup:Group"
create "ledger:Ledger"
"oneGroup:Group" -> "ledger:Ledger" : Create ()
activate "ledger:Ledger" #FFBBBB
create "oneAccount:Account"
create "transaction:Transaction"
"ledger:Ledger" -> "transaction:Transaction" : addTransactionToLedger\n(amount, description, cat, accountFrom, accountTo, type)
deactivate "ledger:Ledger" #FFBBBB

== Act ==

":Test" -> "controller:MemberGetsTheMovementsInAgivenPeriodController" : getOneAccountMovementsFromGroup\n(oneAccount, dateFrom, dateTo, onePerson)
activate "controller:MemberGetsTheMovementsInAgivenPeriodController" #FFBBBB
"controller:MemberGetsTheMovementsInAgivenPeriodController" -> "oneGroup:Group" : getOneAccountMovementsFromGroup\n(oneAccount, dateFrom, dateTo, onePerson)
activate "oneGroup:Group" #FFBBBB
"oneGroup:Group" -> "ledger:Ledger" : getOneAccountMovementsFromGroup\n(oneAccount, dateFrom, dateTo, onePerson)
activate "ledger:Ledger" #FFBBBB
"ledger:Ledger" --> "oneGroup:Group" : getOneAccountMovementsFromGroup
deactivate "ledger:Ledger" #FFBBBB
"oneGroup:Group" --> "controller:MemberGetsTheMovementsInAgivenPeriodController" : getOneAccountMovementsFromGroup
deactivate "oneGroup:Group" #FFBBBB
"controller:MemberGetsTheMovementsInAgivenPeriodController" --> ":Test" : getOneAccountMovementsFromGroup
deactivate "controller:MemberGetsTheMovementsInAgivenPeriodController" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertEquals(expected, real)

@enduml