@startuml

create ":Test"

== Arrange ==

create "group1:Group"
":Test" -> "group1:Group" : new Group
activate "group1:Group" #FFBBBB

create "account1:Account"
create "accountList1:AccountsList"
"group1:Group" -> "accountList1:AccountsList" : new AccountsList

== Act ==

create "account1:Account"
"group1:Group" -> "account1:Account" : createGroupAccount(denomination, description)
activate "account1:Account" #FFBBBB

"account1:Account" -> "accountList1:AccountsList" : addAccountToGroupAccountsList
activate "accountList1:AccountsList" #FFBBBB

"accountList1:AccountsList" -> "account1:Account" : accountCreated
deactivate "accountList1:AccountsList" #FFBBBB

"account1:Account" -> "group1:Group" : accountCreated
deactivate "account1:Account" #FFBBBB

"group1:Group" -> ":Test" : accountCreated
deactivate "group1:Group" #FFBBBB

== Assert ==

":Test" -> ":Test" : assertTrue(accountCreated)

@enduml