@startuml
create ":Test"
== Arrange ==
create "person1:Person"
":Test" -> "person1:Person" : create(name, birthDate, birthPlace)
activate "person1:Person" #FFBBBB
create "categoryList1:CategoryList"
"person1:Person" -> "categoryList1:CategoryList" :  create()
deactivate "person1:Person" #FFBBBB
== Act ==
":Test" -> "person1:Person" : createCategoryAndAddToCategoryList(categoryDescription)
activate "person1:Person" #FFBBBB
"person1:Person" -> "categoryList1:CategoryList" : addCategoryToCategoryList(categoryDescription)
activate "categoryList1:CategoryList" #FFBBBB
create "category1:Category"
"categoryList1:CategoryList" -> "category1:Category" : create(description)
"categoryList1:CategoryList" --> "person1:Person" : categoryCreatedAndAdded
deactivate "categoryList1:CategoryList" #FFBBBB
"person1:Person" --> ":Test" : categoryCreatedAndAdded
deactivate "person1:Person" #FFBBBB
== Assert ==
":Test" -> ":Test" : assertTrue(categoryAddedToCategoryList)
@enduml