@startuml

skinparam DefaultFontSize 20

title US002.1 Sequence Diagram - Happy Case

participant "HTTP Client (Test)"
participant "request:\nRequestBuilder"
participant "resultAction:ResultAction"
participant "mvcResult :MvcResult"
participant "mvc:MockMvc"
participant "restController:US001AreSiblingsControllerRest"
participant "service:US001AreSiblingsService"
participant ":PersonDTOAssembler"
participant "personRepo:PersonRepository"
participant "person1:Person"

autonumber
activate "HTTP Client (Test)" #FFBBBB

== Act ==

create "request:\nRequestBuilder"
"HTTP Client (Test)" -> "request:\nRequestBuilder" : request = get("/areSiblings?\npersonOneEmail=antonio@isep.ipp.pt&\npersonTwoEmail=manuel@isep.ipp.pt")

create "mvc:MockMvc"
"HTTP Client (Test)" -> "mvc:MockMvc" : perform(request)
activate "mvc:MockMvc"  #FFBBBB

autonumber 2.1
create "restController:US001AreSiblingsControllerRest"
"mvc:MockMvc"-->"restController:US001AreSiblingsControllerRest" :areSiblings\n(personOneEmail, \npersonTwoEmail)

autonumber 2.1.1
activate "restController:US001AreSiblingsControllerRest" #FFBBBB
"restController:US001AreSiblingsControllerRest" -> ":PersonDTOAssembler": areSiblingsDTO = createAreSiblingsDTO(personOneEmail, personTwoEmail)

autonumber 2.1.1.1
create "areSiblingsDTO:AreSiblingsDTO"
activate ":PersonDTOAssembler" #FFBBBB
":PersonDTOAssembler" -> "areSiblingsDTO:AreSiblingsDTO":  new AreSiblingsDTO(personOneEmail, personTwoEmail)
deactivate ":PersonDTOAssembler"

autonumber 2.1.2
"restController:US001AreSiblingsControllerRest" -> "service:US001AreSiblingsService": areSiblings = areSiblings(areSiblingsDTO)
activate "service:US001AreSiblingsService" #FFBBBB

autonumber 2.1.2.1
"service:US001AreSiblingsService" -> "personRepo:PersonRepository" : person1 = findPersonByEmail(personOneEmail)
activate "personRepo:PersonRepository" #FFBBBB
deactivate "personRepo:PersonRepository"

"service:US001AreSiblingsService" -> "personRepo:PersonRepository" : person2 = findPersonByEmail(personTwoEmail)
activate "personRepo:PersonRepository" #FFBBBB
deactivate "personRepo:PersonRepository"

"service:US001AreSiblingsService" -> "person1:Person" : validSibling = isSibling(person2)
activate "person1:Person" #FFBBBB

autonumber 2.1.2.3.1
"person1:Person" -> "person1:Person" :  personExistsOnSiblingsList(person2)
"person1:Person" -> "person1:Person" :  checkSameFather(person2)
"person1:Person" -> "person1:Person" :  checkSameMother(person2)

deactivate "person1:Person"
deactivate "service:US001AreSiblingsService"

autonumber 2.1.3
"restController:US001AreSiblingsControllerRest" -> ":PersonDTOAssembler": siblingsDTO = createSiblingsDTO(areSiblings)
activate ":PersonDTOAssembler" #FFBBBB
create "siblingsDTO:SiblingsDTO"

autonumber 2.1.3.1
":PersonDTOAssembler" -> "siblingsDTO:SiblingsDTO": new SiblingsDTO(areSiblings)
deactivate ":PersonDTOAssembler"

autonumber 2.1.4
"restController:US001AreSiblingsControllerRest" -> "mvc:MockMvc": responseEntity(siblingsDTO, HttpStatus.OK)
deactivate "restController:US001AreSiblingsControllerRest"

autonumber 2.2
"mvc:MockMvc" -> "mvc:MockMvc": serialize responseEntity

autonumber 2.3
create "resultAction:ResultAction"
"mvc:MockMvc" -> "resultAction:ResultAction" : create
activate "resultAction:ResultAction" #FFBBBB
deactivate "mvc:MockMvc"

autonumber 3

"HTTP Client (Test)" -> "resultAction:ResultAction" : mvcResult = andReturn()

create "mvcResult :MvcResult"
autonumber 3.1
"resultAction:ResultAction" -> "mvcResult :MvcResult" : create
deactivate "resultAction:ResultAction"

autonumber 4
"HTTP Client (Test)" -> "mvcResult :MvcResult" : response = getResponse
activate "mvcResult :MvcResult" #FFBBBB
deactivate "mvcResult :MvcResult"

"HTTP Client (Test)" -> "mvcResult :MvcResult" : status = getStatus()
activate "mvcResult :MvcResult" #FFBBBB
deactivate "mvcResult :MvcResult"

"HTTP Client (Test)" -> "mvcResult :MvcResult" : result = getContentAsString()
activate "mvcResult :MvcResult" #FFBBBB
deactivate "mvcResult :MvcResult"

== Assert ==
"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(200, status)
"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(expectedResult, result)
deactivate "HTTP Client (Test)"

@enduml

