@startuml

skinparam DefaultFontSize 25

participant "HTTP Client (Test)"
participant "mvcResult:MvcResult"
participant "mvc:MockMvc"
participant "restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest"
participant ":LedgerDTOAssembler"
participant "service\n:US0010_1GetGroupTransactionsInDateRangeService"

== Arrange ==

autonumber

create "inputDTO:\nMemberInfoDTO"
"HTTP Client (Test)" -> "inputDTO:\nMemberInfoDTO": inputDTO = new MemberInfoDTO(personEmail)

activate "HTTP Client (Test)" #FFBBBB
"HTTP Client (Test)" -> "HTTP Client (Test)": inputJson = mapToJson(inputDTO)

== Act ==

create "mvc:MockMvc"
"HTTP Client (Test)" -> "mvc:MockMvc" :GET /groups/{groupDescription}/ledger/transactions/\ninitalDate/{initalDate}/finalDate/{finalDate} {inputJson}
activate "mvc:MockMvc"  #FFBBBB

autonumber 3.1
"mvc:MockMvc" -> "mvc:MockMvc" :  deserialize inputJson

create "infoDTO\n:MemberInfoDTO"
"mvc:MockMvc"-->"infoDTO\n:MemberInfoDTO": create

"mvc:MockMvc"-> "restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest": createGroupTransaction(groupId, infoDTO)
activate "restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest" #FFBBBB

autonumber 3.3.1
"restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest"-> ":LedgerDTOAssembler": transformIntoGetGroupTransactionInDateRangeDTO\n(groupId, personEmail, initalDate, finalDate)
activate ":LedgerDTOAssembler"  #FFBBBB

autonumber 3.3.1.1
create "getGroupTransactionsInDateRangeDTO\n:GetGroupTransactionsInDateRangeDTO"
":LedgerDTOAssembler" -> "getGroupTransactionsInDateRangeDTO\n:GetGroupTransactionsInDateRangeDTO": create(groupId, personEmail, initalDate, finalDate)

":LedgerDTOAssembler" -> "restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest" : getGroupTransactionsInDateRangeDTO
deactivate ":LedgerDTOAssembler"

||| /' space for better visibility '/

autonumber 3.3.2
"restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest"->"service\n:US0010_1GetGroupTransactionsInDateRangeService": getGroupTransactionsInDateRange(getGroupTransactionsInDateRangeDTO)
activate "service\n:US0010_1GetGroupTransactionsInDateRangeService" #FFBBBB

||| /' space for better visibility '/

ref over "service\n:US0010_1GetGroupTransactionsInDateRangeService" : US0010_1GetGroupTransactionsInDateRangeControllerRest_Part2

autonumber 3.3.2.1
"service\n:US0010_1GetGroupTransactionsInDateRangeService" --> "restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest" : List<TransactionShortDTO>
deactivate "service\n:US0010_1GetGroupTransactionsInDateRangeService"

||| /' space for better visibility '/

autonumber 3.3.3
"restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest"->"restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest": selfLink = /groups/{groupId}/ledger/transactions/{id}

||| /' space for added visibility '/

"restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest"-> "transactionShortDTO\n:TransactionShortDTO": add(selfLink)
activate "transactionShortDTO\n:TransactionShortDTO" #FFBBBB
deactivate "transactionShortDTO\n:TransactionShortDTO" #FFBBBB

"restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest" -> "mvc:MockMvc": responseEntity = Response Entity<>\n(List<TransactionShortDTO>,HttpStatus.CREATED)
deactivate "restController\n:US0010_1GetGroupTransactionsInDateRangeControllerRest"

||| /' space for better visibility '/

autonumber 3.4
"mvc:MockMvc" -> "mvc:MockMvc" : serialize responseEntity
"mvc:MockMvc" --> "HTTP Client (Test)" : {jsonResponse}
deactivate "mvc:MockMvc"

||| /' space for better visibility '/

autonumber 4
create "mvcResult:MvcResult"
"HTTP Client (Test)" -> "mvcResult:MvcResult" : create

"HTTP Client (Test)" -> "mvcResult:MvcResult" : status = getStatus()
activate "mvcResult:MvcResult" #FFBBBB
deactivate "mvcResult:MvcResult"

"HTTP Client (Test)" -> "mvcResult:MvcResult" : result = getContentAsString()
activate "mvcResult:MvcResult" #FFBBBB
deactivate "mvcResult:MvcResult"

== Assert ==

"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(200, status)

||| /' space for better visibility '/

"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(expected, result)

||| /' space for better visibility '/

deactivate "HTTP Client (Test)" #FFBBBB

@enduml
