@startuml

autonumber 1
-> "service:US008CreateTransactionService" : addGroupTransaction(createGroupTransactionDTO)
activate "service:US008CreateTransactionService"  #FFBBBB

|||

ref over "service:US008CreateTransactionService" : getAttributes (groupDescription, amount, currency, description, date, type, \ncategoryID, accountFromID, accountToID, groupID, ledger)

|||
autonumber 1.1
"service:US008CreateTransactionService" -> "ledgerRepo:LedgerRepository" : addTransactionToLedger (ledgerID, amount, description, \n date, category, accountFrom, accountTo, type)
activate "ledgerRepo:LedgerRepository" #FFBBBB

autonumber 1.1.1
"ledgerRepo:LedgerRepository" -> "ledgerRepo:LedgerRepository": isIDOnRepository(ledgerID)

"ledgerRepo:LedgerRepository" -> "ledgerRepo:LedgerRepository": ledger = getById(ledgerID)

"ledgerRepo:LedgerRepository"->":LedgerDomainDataAssembler": toData(ledger)
activate ":LedgerDomainDataAssembler" #FFBBBB

autonumber 1.1.3.1
":LedgerDomainDataAssembler"->"ledger:Ledger" : owner = getOwner()
activate "ledger:Ledger" #FFBBBB
deactivate "ledger:Ledger"

":LedgerDomainDataAssembler"->"ledger:Ledger" : creationDate = getCreationDate()
activate "ledger:Ledger" #FFBBBB
deactivate "ledger:Ledger"


create "ledgerJpa:LedgerJpa"
":LedgerDomainDataAssembler"-->"ledgerJpa:LedgerJpa" : create(owner, creationDate)
":LedgerDomainDataAssembler"-->"ledgerRepo:LedgerRepository" : ledgerJpa
deactivate ":LedgerDomainDataAssembler"

create "transaction:Transaction"
autonumber 1.1.4
"ledgerRepo:LedgerRepository"-->"transaction:Transaction": create (amount, description, localDate, category, accountFrom, accountTo, type)

"ledgerRepo:LedgerRepository"->":TransactionDomainDataAssembler": toData(ledger, transaction)
activate ":TransactionDomainDataAssembler" #FFBBBB

autonumber 1.1.5.1
":TransactionDomainDataAssembler"->":LedgerDomainDataAssembler": ledgerJpa = toData(ledger)
activate ":LedgerDomainDataAssembler" #FFBBBB
deactivate ":LedgerDomainDataAssembler" #FFBBBB


":TransactionDomainDataAssembler"-->"transaction:Transaction"
activate "transaction:Transaction" #FFBBBB
ref over "transaction:Transaction" : getTransactionAttributes
"transaction:Transaction"-->":TransactionDomainDataAssembler": amount, currency, \naccountFrom, accountTo, type, id
deactivate "transaction:Transaction" #FFBBBB

create ":TransactionJpa"
":TransactionDomainDataAssembler"->":TransactionJpa" : create(ledgerJpa, amount, currency, description,\n date, category, accountFrom, accountTo, type)

autonumber 1.1.5.5
":TransactionDomainDataAssembler"-->"ledgerRepo:LedgerRepository": transactionJpa
deactivate ":TransactionDomainDataAssembler"

autonumber 1.1.6
"ledgerRepo:LedgerRepository"->"transactionRepo:transactionJpaRepository": : save(transactionJpa)

activate "transactionRepo:transactionJpaRepository" #FFBBBB

deactivate ":TransactionDomainDataAssembler"

autonumber 1.1.6.1
"transactionRepo:transactionJpaRepository"->"transactionRepo:transactionJpaRepository": newTransactionJpa = save(transactionJpa)

"transactionRepo:transactionJpaRepository"-->"ledgerRepo:LedgerRepository": newTransactionJpa
deactivate "transactionRepo:transactionJpaRepository" #FFBBBB

autonumber 1.1.7
"ledgerRepo:LedgerRepository"->"ledgerJpa:LedgerJpa" : addTransaction(owner, newTransactionJpa)
activate "ledgerJpa:LedgerJpa" #FFBBBB

autonumber 1.1.7.1
"ledgerJpa:LedgerJpa"->"ledgerJpa:LedgerJpa" : addTransaction(newTransactionJpa)
deactivate "ledgerJpa:LedgerJpa" #FFBBBB

autonumber 1.1.8
"ledgerRepo:LedgerRepository"->":TransactionDomainDataAssembler":toDomain(newTransactionJpa)
activate ":TransactionDomainDataAssembler" #FFBBBB

autonumber 1.1.8.1
":TransactionDomainDataAssembler"->":TransactionDomainDataAssembler": ownerId = getOwner()

":TransactionDomainDataAssembler" -> ":TransactionJpa"
activate ":TransactionJpa" #FFBBBB
ref over ":TransactionJpa" : getTransactionJpaAttributes
":TransactionJpa" --> ":TransactionDomainDataAssembler" : amount, currency, description, \ndate, type, id, category, accountFrom, accountTo
deactivate ":TransactionJpa"

create "newTransaction:Transaction"
":TransactionDomainDataAssembler"-->"newTransaction:Transaction" : create(amount, description, date , category\n, accountFrom, accountTo, type, id)
":TransactionDomainDataAssembler" --> "ledgerRepo:LedgerRepository" : newTransaction
deactivate ":TransactionDomainDataAssembler"


"ledgerRepo:LedgerRepository" --> "service:US008CreateTransactionService" : newTransaction
deactivate "ledgerRepo:LedgerRepository"

autonumber 1.2
"service:US008CreateTransactionService"->":LedgerDTOAssembler":createTransactionShortDTOFromDomain(newTransaction)
activate ":LedgerDTOAssembler" #FFBBBB

autonumber 1.2.1
":LedgerDTOAssembler"->"newTransaction:Transaction":
activate "newTransaction:Transaction" #FFBBBB

ref over "newTransaction:Transaction" : getNewTransactionAttributes
"newTransaction:Transaction"-->":LedgerDTOAssembler": amount, currency, \naccountFrom, accountTo, type, id
deactivate "newTransaction:Transaction" #FFBBBB

create "transactionShortDTO:TransactionShortDTO"
":LedgerDTOAssembler"->"transactionShortDTO:TransactionShortDTO": create (amount, currency, \naccountFrom, accountTo, type, id)

":LedgerDTOAssembler" --> "service:US008CreateTransactionService" : transactionShortDTO
deactivate ":LedgerDTOAssembler"

autonumber 1.3
<-- "service:US008CreateTransactionService" : transactionShortDTO
deactivate "service:US008CreateTransactionService"

@enduml