@startuml

activate "service:US008CreateTransactionService" #FFBBBB
"service:US008CreateTransactionService" -> "createPersonalTransactionDTO:CreatePersonalTransactionDTO" : personEmail = getPersonEmail()
activate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"  #FFBBBB
deactivate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"

"service:US008CreateTransactionService" -> "createPersonalTransactionDTO:CreatePersonalTransactionDTO" : amount = getAmount()
activate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"  #FFBBBB
deactivate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"

"service:US008CreateTransactionService" -> "createPersonalTransactionDTO:CreatePersonalTransactionDTO" : currency = getCurrency()
activate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"  #FFBBBB
deactivate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"

"service:US008CreateTransactionService" -> "createPersonalTransactionDTO:CreatePersonalTransactionDTO" : description = getDescription()
activate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"  #FFBBBB
deactivate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"

"service:US008CreateTransactionService" -> "createPersonalTransactionDTO:CreatePersonalTransactionDTO" : date = getDate()
activate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"  #FFBBBB
deactivate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"

"service:US008CreateTransactionService" -> "createPersonalTransactionDTO:CreatePersonalTransactionDTO" : type = getType()
activate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"  #FFBBBB
deactivate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"

"service:US008CreateTransactionService" -> "createPersonalTransactionDTO:CreatePersonalTransactionDTO" : category = getCategory()
activate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"  #FFBBBB
deactivate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"

"service:US008CreateTransactionService" -> "createPersonalTransactionDTO:CreatePersonalTransactionDTO" : accountFrom = getAccountFrom()
activate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"  #FFBBBB
deactivate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"

"service:US008CreateTransactionService" -> "createPersonalTransactionDTO:CreatePersonalTransactionDTO" : accountTo = getAccountTo()
activate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"  #FFBBBB
deactivate "createPersonalTransactionDTO:CreatePersonalTransactionDTO"

"service:US008CreateTransactionService" -> "personRepo:PersonRepository" : personID = findPersonByEmail(personEmail)
activate "personRepo:PersonRepository" #FFBBBB
deactivate "personRepo:PersonRepository"

"service:US008CreateTransactionService" -> "ledger:Ledger" : ledger = getByID(personID)
activate "ledger:Ledger" #FFBBBB
deactivate "ledger:Ledger"

"service:US008CreateTransactionService" -> "categoryRepo:CategoryRepository" : categoryID = getByID(categoryID)
activate "categoryRepo:CategoryRepository" #FFBBBB
deactivate "categoryRepo:CategoryRepository"

"service:US008CreateTransactionService" -> "accountRepo:AccountRepository" : accountFrom = getByID(accountFromID)
activate "accountRepo:AccountRepository" #FFBBBB
deactivate "accountRepo:AccountRepository"

"service:US008CreateTransactionService" -> "accountRepo:AccountRepository" : accountTo = getByID(accountToID)
activate "accountRepo:AccountRepository" #FFBBBB
deactivate "accountRepo:AccountRepository"
deactivate "service:US008CreateTransactionService" #FFBBBB

@enduml