@startuml

autonumber 3.3.2.6.2.1
":LedgerDTOAssembler"->"transaction:Transaction" : amount = getAmount()
activate "transaction:Transaction" #FFBBBB
deactivate "transaction:Transaction"

":LedgerDTOAssembler"->"transaction:Transaction" : currency = getCurrency()
activate "transaction:Transaction" #FFBBBB
deactivate "transaction:Transaction"

":LedgerDTOAssembler"->"transaction:Transaction" : accountFrom = getAccountFrom().getDenominationToString()
activate "transaction:Transaction" #FFBBBB
deactivate "transaction:Transaction"

":LedgerDTOAssembler"->"transaction:Transaction" : accountFrom = getAccountTo().getDenominationToString()
activate "transaction:Transaction" #FFBBBB
deactivate "transaction:Transaction"

":LedgerDTOAssembler"->"transaction:Transaction" : type = type.toString()
activate "transaction:Transaction" #FFBBBB
deactivate "transaction:Transaction"

":LedgerDTOAssembler"->"transaction:Transaction" : id = transaction.getId()
activate "transaction:Transaction" #FFBBBB
deactivate "transaction:Transaction"

@enduml