@startuml
skinparam DefaultFontSize 20
title US005.1 Sequence Diagram - Happy Case

participant "HTTP Client (Test)"
participant "resultAction:ResultAction"
participant "inputDTO:\ncreateGroupCategoryInfoDTO"
participant "postRequest:\nRequestBuilder"
participant "mvcResult :MvcResult"
participant "mvc:MockMvc"
participant "info:createGroupCategoryInfoDTO"
participant "CategoryDTOAssembler"
participant "createGroupCategoryDTO:\n createGroupCategoryDTO"
participant "restController:\nUS005_1AdminAddsCategoryControllerRest"


== Arrange ==
autonumber
create "inputDTO:\ncreateGroupCategoryInfoDTO"
activate "HTTP Client (Test)" #FFBBBB
"HTTP Client (Test)" -> "inputDTO:\ncreateGroupCategoryInfoDTO": inputDTO = CreateGroupCategoryInfoDTO(groupDescription,\n personEmail, accountDenomination, accountDescription);
"HTTP Client (Test)" -> "HTTP Client (Test)": inputJson = mapToJson(inputDTO)


== Act ==

create "postRequest:\nRequestBuilder"
"HTTP Client (Test)" -> "postRequest:\nRequestBuilder" : postRequest = Post /addGroupCategory {inputJson}
create "mvc:MockMvc"
"HTTP Client (Test)" -> "mvc:MockMvc" : perform(postRequest)
activate "mvc:MockMvc"  #FFBBBB

autonumber 4.1
"mvc:MockMvc" -> "mvc:MockMvc" : deserialize inputJson
create "info:createGroupCategoryInfoDTO"
"mvc:MockMvc"-->"info:createGroupCategoryInfoDTO" :create

create "restController:\nUS005_1AdminAddsCategoryControllerRest"
"mvc:MockMvc"-> "restController:\nUS005_1AdminAddsCategoryControllerRest": createGroupCategoryDTO (info)
activate "restController:\nUS005_1AdminAddsCategoryControllerRest" #FFBBBB
autonumber 4.3.1
"restController:\nUS005_1AdminAddsCategoryControllerRest"-> "CategoryDTOAssembler":transformToCreateGroupCategorytDTO(info)
activate "CategoryDTOAssembler" #FFBBBB
autonumber 4.3.1.1

"CategoryDTOAssembler" -> "info:createGroupCategoryInfoDTO" : groupDescription = getGroupDescription()
activate "info:createGroupCategoryInfoDTO" #FFBBBB
"CategoryDTOAssembler" -> "info:createGroupCategoryInfoDTO" : personEmail = getPersonEmail();
"CategoryDTOAssembler" -> "info:createGroupCategoryInfoDTO" : categoryDescription = getCategoryDescription();
"CategoryDTOAssembler" -> "info:createGroupCategoryInfoDTO" : categoryDescription = getCategoryDenomination();
deactivate "info:createGroupCategoryInfoDTO"

create "createGroupCategoryDTO:\nCreateGroupCategoryDTO"
"CategoryDTOAssembler" -> "createGroupCategoryDTO:\nCreateGroupCategoryDTO" : createGroupCategoryDTO(personEmail,groupDescription, \ncategoryDenomination, categoryDescription)
activate "createGroupCategoryDTO:\nCreateGroupCategoryDTO" #FFBBBB
autonumber 4.3.1.5.1
"createGroupCategoryDTO:\nCreateGroupCategoryDTO" --> "CategoryDTOAssembler": createGroupCategoryDTO
deactivate "createGroupCategoryDTO:\nCreateGroupCategoryDTO"

autonumber 4.3.1.6
"CategoryDTOAssembler" --> "restController:\nUS005_1AdminAddsCategoryControllerRest" : createGroupCategoryDTO
deactivate "CategoryDTOAssembler"
autonumber 4.3.1.6.1
"restController:\nUS005_1AdminAddsCategoryControllerRest"->"service:US005_1AdminAddsCategoryToGroupService": addCategoryDTOGroup(createGroupCategoryDTO)
activate "service:US005_1AdminAddsCategoryToGroupService" #FFBBBB
autonumber 4.3.1.6.1.1
"service:US005_1AdminAddsCategoryToGroupService" --> "restController:\nUS005_1AdminAddsCategoryControllerRest" : categoryDTO
deactivate "service:US005_1AdminAddsCategoryToGroupService" #FFBBBB

ref over "service:US005_1AdminAddsCategoryToGroupService": US005_1AdminAddsCategoryControllerRest_Part2
autonumber 4.3.2
"restController:\nUS005_1AdminAddsCategoryControllerRest"--> "mvc:MockMvc":responseEntity=responseEntity<>(categoryDTO,HttpStatus.CREATED)
deactivate "restController:\nUS005_1AdminAddsCategoryControllerRest"
autonumber 4.3.4
"mvc:MockMvc" -> "mvc:MockMvc" : serialize responseEntity
create "resultAction:ResultAction"
"resultAction:ResultAction" <-- "mvc:MockMvc" : create
activate "resultAction:ResultAction" #FFBBBB
deactivate "mvc:MockMvc"



autonumber 5
|||
"HTTP Client (Test)" -> "resultAction:ResultAction" : mvcResult = andReturn()

create "mvcResult :MvcResult"
autonumber 5.1
"resultAction:ResultAction" -> "mvcResult :MvcResult" : create
deactivate "resultAction:ResultAction"
autonumber 6
"HTTP Client (Test)" -> "mvcResult :MvcResult" : response = getResponse



activate "mvcResult :MvcResult" #FFBBBB
"HTTP Client (Test)" -> "mvcResult :MvcResult" : status = getStatus()
"HTTP Client (Test)" -> "mvcResult :MvcResult" : result = getContentAsString()
deactivate "mvcResult :MvcResult" #FFBBBB

== Assert ==

"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(201, status)
"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(expectedResult, result)

deactivate "service:US005_1AdminAddsCategoryToGroupService"


@enduml