@startuml
skinparam DefaultFontSize 25

autonumber
 -> "service:US2.1CreateGroupService" : createGroup(createGroupDTO)

autonumber 1.1
activate "service:US2.1CreateGroupService" #FFBBBB
"service:US2.1CreateGroupService" -> "createGroupDTO:CreateGroupDTO" : personEmail = getPersonEmail()
activate "createGroupDTO:CreateGroupDTO" #FFBBBB
deactivate "createGroupDTO:CreateGroupDTO"

"service:US2.1CreateGroupService" -> "personRep:PersonRepository" : person = findPersonByEmail (personEmail)
activate "personRep:PersonRepository" #FFBBBB
deactivate "personRep:PersonRepository"

"service:US2.1CreateGroupService" -> "createGroupDTO:CreateGroupDTO" : groupDescription = getGroupDescription()
activate "createGroupDTO:CreateGroupDTO" #FFBBBB
deactivate "createGroupDTO:CreateGroupDTO"

"service:US2.1CreateGroupService" -> "groupsRep:GroupsRepository" : groupCreated = createGroup(groupDescription, person)
activate "groupsRep:GroupsRepository" #FFBBBB

autonumber 1.4.1
create "groupCreated:Group"
"groupsRep:GroupsRepository" --> "groupCreated:Group" : create(groupDescription, person)

activate "groupCreated:Group" #FFBBBB
autonumber 1.4.1.1
"groupCreated:Group" -> "groupCreated:Group" : addMember(person)
deactivate "groupCreated:Group"

autonumber 1.4.2
"groupsRep:GroupsRepository" -> "groupsRep:GroupsRepository" :add(groupCreated)
deactivate "groupsRep:GroupsRepository"

autonumber 1.5

"service:US2.1CreateGroupService" -> "groupCreated:Group" : groupID = getID()
activate "groupCreated:Group" #FFBBBB
deactivate "groupCreated:Group"

"service:US2.1CreateGroupService" -> ":GroupDTOAssembler" : groupDTO = createGroupDTO (groupID)

autonumber 1.6.1
activate ":GroupDTOAssembler" #FFBBBB
":GroupDTOAssembler" -> "groupID:GroupID" : groupDescription = getDescription()

create "groupDTO:GroupDTO"
":GroupDTOAssembler" --> "groupDTO:GroupDTO" : create(groupDescription)
deactivate ":GroupDTOAssembler"

autonumber 1.7
<-- "service:US2.1CreateGroupService" : groupDTO
deactivate "service:US2.1CreateGroupService"
@enduml