@startuml

skinparam DefaultFontSize 20

autonumber 3.3.2
-> "service:US003AddMemberToGroupService" : createGroup(addMemberDTO)

autonumber 3.3.2.1
activate "service:US003AddMemberToGroupService" #FFBBBB
"service:US003AddMemberToGroupService" -> "addMemberDTO:AddMemberDTO" : personEmail = getPersonEmail()
activate "addMemberDTO:AddMemberDTO" #FFBBBB
deactivate "addMemberDTO:AddMemberDTO"

"service:US003AddMemberToGroupService" -> "personRep:PersonRepository" : person = findPersonByEmail (personEmail)
activate "personRep:PersonRepository" #FFBBBB
deactivate "personRep:PersonRepository"

"service:US003AddMemberToGroupService" -> "addMemberDTO:AddMemberDTO" : groupDescription = getGroupDescription()
activate "addMemberDTO:AddMemberDTO" #FFBBBB
deactivate "addMemberDTO:AddMemberDTO"

"service:US003AddMemberToGroupService" -> "groupsRep:GroupsRepository" : group = findGroupByDescription(groupDescription)
activate "groupsRep:GroupsRepository" #FFBBBB

autonumber 3.3.2.4.1

"groupsRep:GroupsRepository" -> "group:Group" : boolean wasMemberAdded = add(person)
activate "group:Group" #FFBBBB
deactivate "groupsRep:GroupsRepository" #FFBBBB
deactivate "group:Group" #FFBBBB

autonumber 3.3.2.5
"service:US003AddMemberToGroupService" -> ":GroupDTOAssembler" : addedMemberDTO = addMemberDTO (groupID)
activate ":GroupDTOAssembler" #FFBBBB

autonumber 3.3.2.5.1
create "addedMemberDTO:AddedMemberDTO"
":GroupDTOAssembler" -> "addedMemberDTO:AddedMemberDTO" : new AddedMemberDTO(wasMemberAdded, person, group)
deactivate ":GroupDTOAssembler"

 <-- "service:US003AddMemberToGroupService" : addedMemberDTO
deactivate "service:US003AddMemberToGroupService"

@enduml