@startuml

skinparam DefaultFontSize 20

title US003 Sequence Diagram - Happy Case

participant "HTTP Client (Test)"
participant "inputDTO:\naddMemberInfoDTO"
participant "mvcResult :MvcResult"
participant "mvc:MockMvc"
participant "infoDTO:addMemberInfoDTO"
participant "restController:US003AddMemberToGroupControllerRest"
participant ":GroupDTOAssembler"
participant "addMemberInfoDTO:\nAddMemberInfoDTO"
participant "addedMemberDTO:\nAddedMemberDTO"
participant "addMemberDTO:\nAddMemberDTO"
participant "service:\nUS003AddMemberToGroupService"

autonumber 1
create "inputDTO:\naddMemberInfoDTO"
activate "HTTP Client (Test)" #FFBBBB
"HTTP Client (Test)" -> "inputDTO:\naddMemberInfoDTO": inputDTO = new AddMemberInfoDTO\n(personEmail);
"HTTP Client (Test)" -> "HTTP Client (Test)": inputJson = mapToJson(inputDTO)

== Act ==

"HTTP Client (Test)" -> "mvc:MockMvc" : POST /groups/{groupDescription}/members {inputJson}
activate "mvc:MockMvc"  #FFBBBB

autonumber 3.1
"mvc:MockMvc" -> "mvc:MockMvc" :  deserialize inputJson

create "infoDTO:addMemberInfoDTO"
"mvc:MockMvc"->"infoDTO:addMemberInfoDTO": create

create "restController:US003AddMemberToGroupControllerRest"
"mvc:MockMvc"-> "restController:US003AddMemberToGroupControllerRest" : addMember(groupDescription, addMemberInfoDTO)

autonumber 3.3.1
activate "restController:US003AddMemberToGroupControllerRest" #FFBBBB
"restController:US003AddMemberToGroupControllerRest" -> ":GroupDTOAssembler": addMemberDTO = transformIntoAddMemberDTO(addMemberInfoDTO, groupDescription)

autonumber 3.3.1.1

activate ":GroupDTOAssembler" #FFBBBB

":GroupDTOAssembler" -> "addMemberInfoDTO:\nAddMemberInfoDTO": personEmail = getPersonEmail()

activate "addMemberInfoDTO:\nAddMemberInfoDTO" #FFBBBB
deactivate "addMemberInfoDTO:\nAddMemberInfoDTO" #FFBBBB

create "addMemberDTO:\nAddMemberDTO"
":GroupDTOAssembler" -> "addMemberDTO:\nAddMemberDTO": addMemberDTO = new AddMemberDTO(personEmail, groupDescription)
deactivate ":GroupDTOAssembler"

autonumber 3.3.2
"restController:US003AddMemberToGroupControllerRest" -> "service:\nUS003AddMemberToGroupService" : addMemberToGroup(addMemberDTO)
activate "service:\nUS003AddMemberToGroupService" #FFBBBB
|||
ref over "service:\nUS003AddMemberToGroupService" : US003AddMemberToGroup_Part2
autonumber 3.3.2.1
"restController:US003AddMemberToGroupControllerRest" <-- "service:\nUS003AddMemberToGroupService" : addedMemberDTO
|||
deactivate "service:\nUS003AddMemberToGroupService" #FFBBBB

autonumber 3.3.3
"restController:US003AddMemberToGroupControllerRest"->"restController:US003AddMemberToGroupControllerRest": selfLink = /groups/{groupDescription}/members/{personEmail}
"restController:US003AddMemberToGroupControllerRest"-> "addedMemberDTO:\nAddedMemberDTO": add(selfLink)
activate "addedMemberDTO:\nAddedMemberDTO" #FFBBBB
deactivate "addedMemberDTO:\nAddedMemberDTO"

return responseEntity = ResponseEntity<> (addedMemberDTO, HttpStatus.CREATED)
"mvc:MockMvc" -> "mvc:MockMvc" : serialize responseEntity

deactivate "restController:US003AddMemberToGroupControllerRest"

autonumber 3.3.7
"mvc:MockMvc" --> "HTTP Client (Test)" : {jsonResponse}
deactivate "mvc:MockMvc"

create "mvcResult :MvcResult"
autonumber 4
"HTTP Client (Test)" --> "mvcResult :MvcResult" : create

"HTTP Client (Test)" -> "mvcResult :MvcResult" : status = getStatus()
activate "mvcResult :MvcResult" #FFBBBB
deactivate "mvcResult :MvcResult"

"HTTP Client (Test)" -> "mvcResult :MvcResult" : result = getContentAsString()
activate "mvcResult :MvcResult" #FFBBBB
deactivate "mvcResult :MvcResult"


== Assert ==

"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(201, status)
"HTTP Client (Test)" -> "HTTP Client (Test)" : assertEquals(expectedResult, result)
deactivate "HTTP Client (Test)"

@enduml