@startuml
skinparam DefaultFontSize 20

participant "createGroupCategoryDTO: \nCreateGroupCategoryDTO"
participant "service:\nUS005_1AdminAddCategoryToCategoryService"


== Act ==
autonumber
[-> "service:\nUS005_1AdminAddCategoryToCategoryService" : createGroupCategory\n(createGroupCategoryDTO)
activate "service:\nUS005_1AdminAddCategoryToCategoryService" #FFBBBB
autonumber 1.1
"service:\nUS005_1AdminAddCategoryToCategoryService" -> "createGroupCategoryDTO: \nCreateGroupCategoryDTO" : personEmail = getPersonEmail()
activate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB
deactivate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB

"service:\nUS005_1AdminAddCategoryToCategoryService" -> "createGroupCategoryDTO: \nCreateGroupCategoryDTO" : groupDescription = getGroupDescription())
activate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB
deactivate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB

"service:\nUS005_1AdminAddCategoryToCategoryService" -> "createGroupCategoryDTO: \nCreateGroupCategoryDTO" : categoryDenomination = getCategoryDenomination()
activate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB
deactivate "createGroupCategoryDTO: \nCreateGroupCategoryDTO"  #FFBBBB


"service:\nUS005_1AdminAddCategoryToCategoryService"->"groupRep:GroupRepository":group = findGroupByDescription\n(groupDescription)
activate "groupRep:GroupRepository" #FFBBBB
deactivate "groupRep:GroupRepository"

"service:\nUS005_1AdminAddCategoryToCategoryService"->"personRep:PersonRepository": person = findPersonByEmail(personEmail)
activate "personRep:PersonRepository" #FFBBBB
deactivate "personRep:PersonRepository"

"service:\nUS005_1AdminAddCategoryToCategoryService"->"person:Person": personID = getID()
activate "person:Person" #FFBBBB
deactivate "person:Person"

"service:\nUS005_1AdminAddCategoryToCategoryService"->"group:Group": validateAdmin = isGroupAdmin(personID)
activate "group:Group" #FFBBBB
deactivate "group:Group"

"service:\nUS005_1AdminAddCategoryToCategoryService"->"group:Group": groupID = getID()
activate "group:Group" #FFBBBB
deactivate "group:Group"

"service:\nUS005_1AdminAddCategoryToCategoryService"->"categoryRep:CategoryRepository": createCategory(categoryDenomination, groupID)
activate "categoryRep:CategoryRepository" #FFBBBB

participant ":CategoryDomainDataAssembler"
autonumber 1.9.1
create "category:Category"
"categoryRep:CategoryRepository"-->"category:Category":create(categoryDenomination, groupID)
"categoryRep:CategoryRepository"->":CategoryDomainDataAssembler":toData(category)
autonumber 1.9.2.1
activate ":CategoryDomainDataAssembler" #FFBBBB
":CategoryDomainDataAssembler"->"category:Category" : groupID = getID()
activate "category:Category" #FFBBBB
":CategoryDomainDataAssembler"->"category:Category" : categoryDenomination = getCategoryDenomination()
deactivate "category:Category"
create "categoryJpa:CategoryJpa"
":CategoryDomainDataAssembler"-->"categoryJpa:CategoryJpa" : create(groupID,categoryDenomination)
":CategoryDomainDataAssembler"-->"categoryRep:CategoryRepository" : categoryJPA
deactivate ":CategoryDomainDataAssembler" #FFBBBB
autonumber 1.9.3
|||
"categoryRep:CategoryRepository"->"categoryRep:CategoryRepository": save(categoryJpa)
|||
"categoryRep:CategoryRepository"->":CategoryDomainDataAssembler":toDomain(categoryJpa)
activate ":CategoryDomainDataAssembler" #FFBBBB
autonumber 1.9.4.1
":CategoryDomainDataAssembler"->"categoryJpa:CategoryJpa" : groupID = getCategoryIdJpa()
activate "categoryJpa:CategoryJpa" #FFBBBB
":CategoryDomainDataAssembler"->"categoryJpa:CategoryJpa" : categoryDenomination = getDenomination()
deactivate "categoryJpa:CategoryJpa"
participant ":CategoryDTOAssembler"
create "savedCategory:Category"
":CategoryDomainDataAssembler"-->"savedCategory:Category":create(categoryDenomination, groupID)
":CategoryDomainDataAssembler"-->"categoryRep:CategoryRepository" : savedCategory

deactivate ":CategoryDomainDataAssembler" #FFBBBB

autonumber 1.9.5
"service:\nUS005_1AdminAddCategoryToCategoryService"<--"categoryRep:CategoryRepository": savedCategory
deactivate "categoryRep:CategoryRepository"
autonumber 1.10

"service:\nUS005_1AdminAddCategoryToCategoryService"->":CategoryDTOAssembler": createCategoryDTOFromCategory(savedCategory)
activate ":CategoryDTOAssembler" #FFBBBB
autonumber 1.10.1
":CategoryDTOAssembler"->"savedCategory:Category": denomination = getDenomination()
activate "savedCategory:Category" #FFBBBB
":CategoryDTOAssembler"->"savedCategory:Category": groupID = getID()
deactivate "savedCategory:Category"
create "categoryDTO:CategoryDTO"
":CategoryDTOAssembler"--> "categoryDTO:CategoryDTO" : create (denomination, groupID)
"service:\nUS005_1AdminAddCategoryToCategoryService"<--":CategoryDTOAssembler": categoryDTO
deactivate ":CategoryDTOAssembler" #FFBBBB
autonumber 1.11
[<-- "service:\nUS005_1AdminAddCategoryToCategoryService" : categoryDTO
deactivate "service:\nUS005_1AdminAddCategoryToCategoryService"
@enduml